### ISSUE TITLE
AppImages on releases page

### ISSUE THREAD

**Issue by probonopd** [aferrero2707/PhotoFlow#103]
Is there anything preventing the AppImages from going on the release page? Can I help?

**Comment by aferrero2707** [comment]
Absolutely not, apart from the fact that all this is still quite experimental in the PhotoFlow case.

However things are progressing quite well and fast, so I hope to have a first release of the photoflow recipe(s) in less than one month.

By the way, I plan to have two recipes: one to build the appimage from the Ubuntu package, and one from Git sources.

As a side note, I am also working on an AppImage for GIMP, which includes additional things like the MyPaint brushes, the G'MIC plug-in, and the photoflow plug-in for loading RAW images directly within Gimp. The BABL/GEGL/GIMP/PhotoFlow parts are built from Git sources, and G'MIC is built from the latest source release (1.7.5_pre at this time). Are you also interested into this?

**Comment by probonopd** [comment]
Awesome! Yes, I'm also highly interested in your GIMP recipe.

**Comment by aferrero2707** [comment]
The current Gimp+gmic+PhF recipe is kept as a gist: https://gist.github.com/aferrero2707/2da99aae425eca8c8afb61b3fb5532f9

If you have time to have a look, I'm open to any suggestions.

For compiling and installing the sources, it uses a little trick: the install prefix is set to "/zzz" (to avoid mixing with system libraries and binaries), and then it is converted to "././" exactly like it is done for "/usr".

**Comment by probonopd** [comment]
Which system and version are you using for building?

**Comment by aferrero2707** [comment]
I'm building on Linux Mint 17.2 64 bits, with some packages from "dhor/myway"and "pmjdebruijn/darktable-unstable" PPAs.
