### ISSUE TITLE
Photoflow exits with error message and return code 134

### ISSUE THREAD

**Issue by scit2010** [aferrero2707/PhotoFlow#106]
How to reproduce:
1. Run Photoflow from command line.
2. Open an image in Photoflow.
3. Exit the program by its Exit button.

Expected behaviour:
The program terminates without error message and exit code 0.

Actual behaviour:
The program terminates with the error message: "VIPS:ERROR:buffer.c:377:vips_buffer_undone: assertion failed: (cache->thread == g_thread_self())" and exit code 134.

Here is the complete debug output after clicking the exit button:
MainWindow::on_delete_event(): npages=1
MainWindow::on_delete_event(): tab=0  w=0x4043920
MainWindow::on_delete_event(): removing tab #0
PF::MainWindow::remove_tab() called.
  editor->get_image()->is_modified(): 0
Active image: 0
PF::Image::update(): waiting for rebuild_done....
~ImageEditor(): deleting image
Pipeline::~Pipeline() called.
Pipeline::~Pipeline(): unref of nodes[i]->image
Pipeline::~Pipeline(): deleting processor
ImageReaderPar::~ImageReaderPar(): raster_image=0x7f399400ead0
ImageReaderPar::~ImageReaderPar(): raster_image->get_nref()=2
~OpParBase(): deleting operation 0x7f3994001300
Pipeline::~Pipeline(): processor deleted
Pipeline::~Pipeline(): deleting blender
~OpParBase(): deleting operation 0x7f3994009510
Pipeline::~Pipeline(): blender deleted
Pipeline::~Pipeline(): deleting sinks
Pipeline::~Pipeline(): deleting sink #0
Pipeline::~Pipeline(): sink #0 deleted
Pipeline::~Pipeline(): all sinks deleted
Pipeline::~Pipeline() called.
Pipeline::~Pipeline(): unref of nodes[i]->image
Pipeline::~Pipeline(): deleting processor
ImageReaderPar::~ImageReaderPar(): raster_image=0x7f399400ead0
ImageReaderPar::~ImageReaderPar(): raster_image->get_nref()=1
~OpParBase(): deleting operation 0x7f39940d7bb0
Pipeline::~Pipeline(): processor deleted
Pipeline::~Pipeline(): deleting blender
~OpParBase(): deleting operation 0x7f39940e3630
Pipeline::~Pipeline(): blender deleted
Pipeline::~Pipeline(): deleting sinks
Pipeline::~Pipeline(): deleting sink #0
Deleting image area
**
VIPS:ERROR:buffer.c:377:vips_buffer_undone: assertion failed: (cache->thread == g_thread_self())

I've built with the latest git master branches of Photoflow and VIPS.

Is this something that happens only to me or do others have the same problem?

**Comment by aferrero2707** [comment]
Could you try with the "stable" photoflow branch?

The master brach corresponds to the official release 0.2.6, which is rather old now. As I'm planning a new release in few days from now, which will be based on the current stable branch, it would be interesting to know if the problem is still present in stable or not.

Thanks!

**Comment by scit2010** [comment]
I tried, but now the build breaks at gexiv2. It claims that aclocal 1.14 is missing: 

CDPATH="${ZSH_VERSION+.}:" && cd <Workspace>/PhotoFlow/src/external/gexiv2 && /bin/bash <Workspace>/PhotoFlow/src/external/gexiv2/build-aux/missing aclocal-1.14 -I m4 
<Workspace>/PhotoFlow/src/external/gexiv2/build-aux/missing: Zeile 81: aclocal-1.14: Kommando nicht gefunden.
WARNING: 'aclocal-1.14' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>

<Workspace> is a placeholder for my actual workspace path.
I have automake 1.15, libgexiv2-2 (version 0.10.3-2) and libgexiv2-dev installed on my system. However aclocal is not found. Is there a way to skip the gexiv2 build if I have it already installed here?

**Comment by aferrero2707** [comment]
Please pass "-DBUNDLED_GEXIV2=OFF" to the cmake invocation.

I should make the bundled GExiv2 an option, not the default.

There reason for having it is that some Ubuntu PPA mess-up with the versions of EXIV2 and GExiv2 libraries.

**Comment by Joermungand** [comment]
Here’s a quick workaround I use in the PKGBUILD for Arch:

sed -i "s/am__api_version='1.14'/am__api_version='1.15'/" 
src/external/gexiv2/configure

just before issuing the cmake command.

**Comment by scit2010** [comment]
Thank you. 
I've extended the cmake invocation as proposed by aferrero2707 and integrated it into my latest pull request.

**Comment by aferrero2707** [comment]
@Joermungand for Arch there is actually no reason for using the bundled Gexiv2, which as I said should be made not the default (I will include this in the next bunch of commits).

So please use "-DBUNDLED_GEXIV2=OFF" for your Arch builds as well...

Thanks!

**Comment by Joermungand** [comment]
Will do. Thank you. This will also reduce compile time a bit.

**Comment by scit2010** [comment]
OK, back to my original problem: yes, the error also occurs in the stable branch. I'm on a current Debian testing, 64 bit.

**Comment by aferrero2707** [comment]
Could you compile with -DCMAKE_BUILD_TYPE=Debug, run photoflow through gdb and send me the output of the "bt" gdb command after the crash occurs? This will help me locate the origin of the problem, which I cannot reproduce on my system...

**Comment by scit2010** [comment]
Here is the debug output:
[Issue 106 - gdb report of program exit.txt](https://github.com/aferrero2707/PhotoFlow/files/455548/Issue.106.-.gdb.report.of.program.exit.txt)

**Comment by aferrero2707** [comment]
I have pushed a fix for the crash at program exit, could you recompile the stable branch and check if it works for you?

Thanks!

**Comment by scit2010** [comment]
It works fine now, thank you!
