### ISSUE TITLE
Photoflow does not build with the latest gimp 

### ISSUE THREAD

**Issue by beew** [aferrero2707/PhotoFlow#110]
Hi, trying to build photoflow (both the stable and master branches  from git) with the latest gimp 2.9 and fail with
```
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options. ...
```

Without gimp PF built successfully.

OS is Ubuntu 16.04 64 bit.

**Comment by aferrero2707** [comment]
Could you send me the full compile output, to see where exactly it fails?

Thanks!

Il 28/set/2016 13:18, "beew" <notifications@github.com> ha scritto:

**Comment by beew** [comment]
Here it is
[outpput.txt](https://github.com/aferrero2707/PhotoFlow/files/497941/outpput.txt)

**Comment by aferrero2707** [comment]
The build script does not accept ```-j 4``` as an argument, try invoking it without arguments, like this

    INSTALL_PREFIX=your_install_folder ./build.sh

**Comment by beew** [comment]
works now, thanks.

**Comment by aferrero2707** [comment]
You are welcome!
