### ISSUE TITLE
how to disable pfgimp?

### ISSUE THREAD

**Issue by beew** [aferrero2707/PhotoFlow#111]
This is a bit of a mystery.  I tried pfgimp a bit but want to revert back to darktable but somehow can't do it. I removed pfgimp from gimp's plugin folder. That doesn't work. I removed gimp's and photoflow's config folders, and removed photoflow's symlink to /usr/local/bin and still doesn't work. Finally I renamed photoflow's directory, gimp still tries to open the sample picture with photoflow (but broken since the folder is named) 

I compiled both gimp and photoflow myself and they are in my $HOME. OS is Ubuntu 16.04

**Comment by aferrero2707** [comment]
Where did you install pfgimp? Did you also remove pfgimp-load?

In fact, you only need to remove pfgimp-load. Pfgimp works like a filter
plugin a la gmic, and is not used for loading images...

Anyhow, the main problem is that gimp doesn't have a way to enable/disable
plugins.

**Comment by beew** [comment]
I compiled photoflow and then found pfgmp and pfgmp in the build/src folder, I copied pfgmp to .config/GIMP/2.9/plug-ins. It worked. I then remove pfgmp from the plug-ins folder and it still works!

**Comment by aferrero2707** [comment]
What is the output of

    find /usr -name "pfgimp*"

and

    find $HOME -name "pfgimp*"

on you system?

Il 01/ott/2016 18:51, "beew" <notifications@github.com> ha scritto:

I compiled photoflow and then found pfgmp and pfgmp in the build/src
folder, I copied pfgmp to .config/GIMP/2.9/plug-ins. It worked. I then
remove pfgmp from the plug-ins folder and it still works!

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/aferrero2707/PhotoFlow/issues/111#issuecomment-250922968>,
or mute the thread

**Comment by beew** [comment]
Hi,

Hummm

find $HOME-name "pfgimp*" returns

/home/beew/gimp-2.9/lib/gimp/2.0/plug-ins/pfgimp-load
//home/beew/gimp-2.9/lib/gimp/2.0/plug-ins/pfgimp

So it appears that they were installed in gimp's path when I compiled photoflow. I thought I had to copy pfgimp to .config/GIMP/plug-ins manually as  one of your blog posts instructed. But I think in this case it doesn't require root permission to enter gimp's directory so make install automatically put the plugins there.

Thanks, the mystery is solved. :)

**Comment by aferrero2707** [comment]
Yes, in the latest code I automatically install the plug-ins in the appropriate directory, according to where GIMP was installed.

I suggest you to only delete pfgimp-load. This way, you will be able to use darktable to load RAWs, and you will still have the photoflow plug-in at hand under "Filters -> Photoflow..." in case you'd like to use it...
