### ISSUE TITLE
Failure to Export

### ISSUE THREAD

**Issue by assaft** [aferrero2707/PhotoFlow#113]
Hi,
Photoflow 0.2.7, on Windows 10, converting an ORF file. 
My development has the following layers:
original (used only for comparison)
sharpening
crop
scale
curves
basic adjustments
curves
noise reduction
raw

Some export scenarios:
Exporting to JPEG: takes about 30 seconds, and results in a file of 0 bytes
Exporting to TIFF: takes about 30 seconds, and results in a file of 172,294 bytes (too small, not viewable). Attached below.
Disabling the scale and crop layers and then exporting to JPEG/TIFF:  photoflow.exe crashes after 2 seconds.
Disabling the scale, crop and sharpening layers and then exporting to JPEG/TIFF:  takes 2:25 seconds and looks good.

Files:
[RAW](https://dl.dropboxusercontent.com/u/21642925/P9040307.ORF) [PFI](https://dl.dropboxusercontent.com/u/21642925/P9040307.pfi) [Small TIFF](https://dl.dropboxusercontent.com/u/21642925/P9040307.tif)

**Comment by aferrero2707** [comment]
Hi!

your sample file allowed me to spot a bug in the "impulse NR" filter, as well as some inefficient processing of the sharpening filter.

Could you test this new version? https://filebin.net/ltg0yq0a3r5srkn1

The noise reduction is still significantly slow when saving, but the rest of the layers now should not introduce additional computing time (not significantly).

Thanks!

**Comment by assaft** [comment]
Thanks. Can you send me zipped binaries to copy over the old ones? I don't manage to run the installer. For some reason it quits immediately and I still don't know where the problem is. I collected info from the windows event viewer but it doesn't tell enough. 
Alternatively, Is there a verbose mode for the installer where it gives more info about its processing? or any log file where I can look? 
I had the same problem when I first installed Photoflow, but after some hours/days I tried again and it suddenly worked. I remember the first thing that jumps is a Windows alert asking if I want to confirm the installation. Maybe the installer do some windows checks in the beginning and one of them fails.

**Comment by aferrero2707** [comment]
Here you can find the zipped binaries: https://filebin.net/xsq0sq8icpvktm1l

I have to admit that I am not really an expert of windows installers, and I do not have a Win10 system to check myself...

**Comment by assaft** [comment]
All scenarios work great now. Thanks.
