### ISSUE TITLE
Crash when opening 16bit pngs

### ISSUE THREAD

**Issue by waxfingers** [aferrero2707/PhotoFlow#125]
OSX, latest build. Photoflow crashes when opening 16bit pngs

**Comment by aferrero2707** [comment]
I have tested with a coupe of 16-bit PNG samples (with and without alpha channel), and I do not get any crashes... Is it still crashing in your case with the latest versions? If yes, could you share a sample?

Thanks!

**Comment by waxfingers** [comment]
> Is it still crashing in your case with the latest versions?
**No**
So many improovements since the version's above mentioned; maybe I should have keep up with the issues and close this (?)... For clarity sake (sorry if it seems obvious) shall I close the issues I opened that have been fixed? Thanks

**Comment by aferrero2707** [comment]
Very good!

I prefer to close the issues myself, as otherwise there might be some "false positives" that I might miss.

Thanks!
