### ISSUE TITLE
XML files with duplicated names (save for the case)

### ISSUE THREAD

**Issue by assaft** [aferrero2707/PhotoFlow#129]
The installation package contains files like:
vnd.ms-excel.template.macroEnabled.12.xml
vnd.ms-excel.template.macroenabled.12.xml
and:
vnd.ms-powerpoint.presentation.macroenabled.12.xml
vnd.ms-powerpoint.presentation.macroEnabled.12.xml
(see more examples below)
that look the same in case-insensitive OS like Windows. 
As a result, the OS asks the user which file to maintain in the photoflow directory and which ones to delete.  
If both versions are needed in the package, it would be better to distinguish between them based on something other than the case.

The files that the OS reports on (hopefully the full list):
vnd.ms-excel.template.macroenabled.12.xml
vnd.ms-powerpoint.presentation.macroEnabled.12.xml
vnd.ms-powerpoint.template.macroenabled.12.xml
vnd.ms-word.template.macroenabled.12.xml
vnd.ms-excel.sheet.binary.macroenabled.12.xml
vnd.ms-word.document.macroenabled.12.xml
vnd.ms-excel.sheet.macroEnabled.12.xml

**Comment by aferrero2707** [comment]
This will be fixed in next official windows package
