### ISSUE TITLE
Crash when resizing main window OSX

### ISSUE THREAD

**Issue by waxfingers** [aferrero2707/PhotoFlow#132]
OSX 10.11.6 and the first december build of Photoflow. I was looking for the save presets buttons, crossed my mind that maybe the GUI was resized (in relatioon to my screen size) and so the before mentioned might had gone under the rug; so tried to resize the window and PF repeatidely crashed.
Tried from the corner and from the sides too. Cheers =)

**Comment by waxfingers** [comment]
I'm closing this issue as I'm unable to reproduce the crashes anymore =)

**Comment by aferrero2707** [comment]
Thanks. I've also never observed such a problem...
