### ISSUE TITLE
Crash when opening raw files

### ISSUE THREAD

**Issue by waxfingers** [aferrero2707/PhotoFlow#141]
The lastest mac build => photoflow-20170401.app.dmg is crashing on my machine (osx 10.11.6) when opening raws. Tested with panasonic, nikon and canon files. This behavior does not occur in the 25 feb release 🐠

**Comment by aferrero2707** [comment]
I confirm the crash.

I have uploaded a new OSX package, built from the current stable branch, which works fine on my system. Could you get it from [here](https://github.com/aferrero2707/PhotoFlow/releases/download/continuous/photoflow-20170512.app.dmg) and check if it solves the issue for you as well?

Thanks!

**Comment by waxfingers** [comment]
PERFECT! Thanks Carmelo =)  

![pf_latest](https://cloud.githubusercontent.com/assets/13238340/25995495/6f85effa-370a-11e7-88f9-630fac5469c6.jpg)
