### ISSUE TITLE
CA_correct_RT.cc

### ISSUE THREAD

**Issue by heckflosse** [aferrero2707/PhotoFlow#164]
May I suggest to not use the Amaze header for [ca-correction source](https://github.com/aferrero2707/PhotoFlow/blob/stable/src/rt/rtengine/CA_correct_RT.cc)

Also, there is a newer, [faster version](https://github.com/Beep6581/RawTherapee/issues/4012#issuecomment-323349301) available.

**Comment by aferrero2707** [comment]
Thanks for pointing this out, most likely the mistake comes from some stupid copy-paste...

The header is now fixed in the stable branch.

I'm aware of the recent optimizations you introduced in the CA correction code, and it is definitely in my plans to port them into photoflow!

**Comment by heckflosse** [comment]
Ok, thank you :+1:
