### ISSUE TITLE
Issue in color profile conversion in Ubuntu.

### ISSUE THREAD

**Issue by mridul1618** [aferrero2707/PhotoFlow#165]
I am using Ubuntu 17.04. I downloaded the latest stable build of PhotoFlow (v0.2.8) and tried to follow thr process described here: [photoflow blogspot](http://photoflowblog.blogspot.in/2016/10/non-destructive-lab-editing-with-gimp.html). Nothing happens, I get a warning on terminal saying `ConvertColorspacePar::build(): missing embedded profile, returning input image`.

**Comment by aferrero2707** [comment]
I will try to reproduce the problem. I suspect that this is due to the use of the default sRGB profile in GIMP.

**Comment by mridul1618** [comment]
I used photoflow both directly from appimage and via gimp as filter; encountered the same problem both times.

**Comment by aferrero2707** [comment]
Could you try with the latest version, making sure that you select "embedded (sRGB)" as the input profile of the image loader layer? That should cure the missing profile issue.

**Comment by mridul1618** [comment]
Thank you for the response. I'd see if it works with the latest version and inform here if the problem persists.

**Comment by aferrero2707** [comment]
Closing since there were no reports of further problems.
