### ISSUE TITLE
Windows installer - default installation path incorrect

### ISSUE THREAD

**Issue by paynekj** [aferrero2707/PhotoFlow#17]
By default the Windows installer suggests the destination folder: C:\Users\UserName\AppData\Local\Photoflow

This location is for data, not applications, which should go into Programs Files\Program Files (x86)

**Comment by aferrero2707** [comment]
The reason for the strange installation location is that I consider the windows version quite a bit experimental, and that I have no way to test the installer with all the supported windows versions, therefore I decided not to interfere with system folders for the moment... normally photoflow should run without problems even from this unusual installation path.

Anyhow, thanks a lot for reporting this issue, I'll leave it open as a reminder that I should fix that at some point.

And welcome to photoflow! I hope you will enjoy it.

**Comment by aferrero2707** [comment]
Fixed in latest windows installer. The installation path is now taken from the PROGRAMFILES variable exported by NSIS.
