### ISSUE TITLE
Highlight recovery

### ISSUE THREAD

**Issue by Robndrwrth** [aferrero2707/PhotoFlow#171]
I have noticed a problem when recovering highlights using the latest version (osx-20171215_1252-git-stable-5fb36718dd79d181c5cabfd8f99f7) but also checked with the 2 Dec version and that also had the problem. When I select blending and put in negative exposure compensation, initially whilst 'caching' (amber indicator) the highlight recovery looks what I would expect but when it goes to 'ready' the recovered bit goes green. Example raw file, pfi and jpg showing effect are attached (not a photo of any great merit but it shows the problem well). Note that the jpg has been converted to srgb but the effect is there with the working colourspace, in this case LAB but it also occurs with Prophoto etc. I have tried various options of clipping etc but this seems to happen with all options. I've just moved to High Sierra (10.13.2) but also tried this on El Capitan (10.11.6) with a different mac and display and the problem is the same. Let me know if I can help with further info. 

[Photoflow highlight recovery problem.zip](https://github.com/aferrero2707/PhotoFlow/files/1579721/Photoflow.highlight.recovery.problem.zip)

Thanks
Rob

**Comment by aferrero2707** [comment]
Thanks, I will have a look at this as soon as possible, but probably only right after the Christmas vacations... I will post my progresses here as soon as I have something new.

Thanks!

**Comment by Robndrwrth** [comment]
No rush, have a good holiday.

Merry Christmas

**Comment by aferrero2707** [comment]
The "clip" mode seems to work properly:

<img width="1280" alt="screen shot 2017-12-21 at 21 39 08" src="https://user-images.githubusercontent.com/6229237/34274048-4199cfc0-e697-11e7-87f2-a0f53b82947a.png">

**Comment by Robndrwrth** [comment]
Yes, I have no problems with the clip mode only blend which I used to try to recover some of the lost cloud detail. Previously I have occasionally used this successfully but I’m not sure at which version it stopped working well. As stated in the issue report the image shown during caching looks quite good with lots of recovered cloud but then this turns green when ‘ready’.

Thanks again.

**Comment by aferrero2707** [comment]
If you still have a version packages before the 24th of November, it should still provide a working "blend" mode.

**Comment by Robndrwrth** [comment]
Thanks I’ll try that.

**Comment by Robndrwrth** [comment]
Just tried the ‘linear gamma' version from 24 Nov, this works fine for the ‘blend’ mode but has the problem of not correctly dealing with LAB directly in the RAW developer. This is not a problem as I can convert to RGB initially and then convert to LAB if needed. I know this works from earlier use.

I also tried the earlier stable version from 2 Oct but that does not get on with High Sierra. It did not start at all and the OS displayed a message about it not working with this version of the OS.

Anyway I have a nice work around so thanks very much for that.

**Comment by aferrero2707** [comment]
I think I found the issue, and was easy to fix... you should get an updated OSX package in one hour or so. Could you check if HL recovery works correctly again for you?

Thanks!

**Comment by Robndrwrth** [comment]
Just checked the updated package and the HL recovery is ok. Thanks for all your work. Have a good holiday!

**Comment by aferrero2707** [comment]
Thanks, nice holidays to you as well!
