### ISSUE TITLE
i386 build

### ISSUE THREAD

**Issue by salvadhor** [aferrero2707/PhotoFlow#174]
I've revived PhotoFlow autobuild on Launchpad lately (PPA for Ubuntu/Mint). Unfortunately, i386 build fails with:

/Cr2Decompressor.cpp.o -c /<<BUILDDIR>>/photoflow-git-2.9+git20180129/src/external/rawspeed/src/librawspeed/decompressors/Cr2Decompressor.cpp
In file included from /<<BUILDDIR>>/photoflow-git-2.9+git20180129/src/external/rawspeed/src/librawspeed/decoders/RawDecoderException.h:24:0,
                 from /<<BUILDDIR>>/photoflow-git-2.9+git20180129/src/external/rawspeed/src/librawspeed/decompressors/AbstractLJpegDecompressor.h:26,
                 from /<<BUILDDIR>>/photoflow-git-2.9+git20180129/src/external/rawspeed/src/librawspeed/decompressors/Cr2Decompressor.h:23,
                 from /<<BUILDDIR>>/photoflow-git-2.9+git20180129/src/external/rawspeed/src/librawspeed/decompressors/Cr2Decompressor.cpp:22:
/<<BUILDDIR>>/photoflow-git-2.9+git20180129/src/external/rawspeed/src/librawspeed/decompressors/AbstractLJpegDecompressor.h: In instantiation of ‘std::array<rawspeed::HuffmanTable*, N_COMP> rawspeed::AbstractLJpegDecompressor::getHuffmanTables() const [with int N_COMP = 3]’:
/<<BUILDDIR>>/photoflow-git-2.9+git20180129/src/external/rawspeed/src/librawspeed/decompressors/Cr2Decompressor.cpp:119:37:   required from ‘void rawspeed::Cr2Decompressor::decodeN_X_Y() [with int N_COMP = 3; int X_S_F = 2; int Y_S_F = 2]’
/<<BUILDDIR>>/photoflow-git-2.9+git20180129/src/external/rawspeed/src/librawspeed/decompressors/Cr2Decompressor.cpp:87:28:   required from here
/<<BUILDDIR>>/photoflow-git-2.9+git20180129/src/external/rawspeed/src/librawspeed/common/RawspeedException.h:79:34: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 5 has type ‘std::array<rawspeed::HuffmanTable*, 4>::size_type {aka unsigned int}’ [-Werror=format=]
   rawspeed::ThrowException<CLASS>("%s, line " STR(__LINE__) ": " fmt,          \
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

(full log https://launchpadlibrarian.net/355135218/buildlog_ubuntu-artful-i386.photoflow-git_1%3A2.9+git20180129-1218~ubuntu17.10.1_BUILDING.txt.gz)

Is that mean that support for i386 is dropped?

**Comment by aferrero2707** [comment]
Closing since maintaining and testing the i386 compatibility is currently too much effort.
