### ISSUE TITLE
Allow disabling all bundled libraries

### ISSUE THREAD

**Issue by jtojnar** [aferrero2707/PhotoFlow#175]
Could you add an option for disabling the rest of the bundled libraries? At least `BUNDLED_RAWSPEED` or even `BUNDLED_ALL`

**Comment by aferrero2707** [comment]
In the current `stable` branch all bundled libraries are optional, and disable by default. The only exception is RawSpeed, for two good reasons:
* it is not provided as a separate package in most Linux distributions
* the list of supported RAW files is considered part of the specific characteristics of a given release, and is not supposed to change from one system to another. That's the main reason why I am against using a system-provided RawSpeed library, and on this I follow the logic of the Darktable developers...

By the way, thanks for binging Photoflow into NixOS! I would really encourage you to consider having "bleeding edge" builds from the `stable` branch in addition to the 0.2.8 release, as they are likely to be even more stable...

At the moment I am still far from being ready for a new major release.
