### ISSUE TITLE
non-starting photoflow-osx-20181107_1248-git-stable-a32ba26625ffabbbae38429145bd25d0cfad9898

### ISSUE THREAD

**Issue by waxfingers** [aferrero2707/PhotoFlow#177]
Hey Doctor Ceeto, **latest macos phf does NOT start.**
The CL works fine, very nice addition BTW 
you were right about scale algo 👍

Mojave 10.14.1
photoflow-osx-20181107_1248-git-stable-a32ba26625ffabbbae38429145bd25d0cfad9898

[crash_photoflow-osx-20181107_1248-git-stable-a32ba26625ffabbbae38429145bd25d0cfad9898.txt](https://github.com/aferrero2707/PhotoFlow/files/2559994/crash_photoflow-osx-20181107_1248-git-stable-a32ba26625ffabbbae38429145bd25d0cfad9898.txt)

**Comment by aferrero2707** [comment]
Issue solved with commit fbd1fd779dbabe1b3f787e1fb535be86215c0094.
Closing.
