### ISSUE TITLE
Opening DNG file initially doesn't display correct image

### ISSUE THREAD

**Issue by paynekj** [aferrero2707/PhotoFlow#18]
When I open a .DNG file I get a very strange image displayed initially.

![untitled](https://cloud.githubusercontent.com/assets/11903737/7102987/4ce81576-e08c-11e4-8457-d5f894e77a7c.png)

Pressing the Zoom - then gives me the image correctly, but I get back the the incorrect image by zooming +

**Comment by aferrero2707** [comment]
This is expected (although not very nice, and should be corrected...). In photoflow, the loading and the processing of RAW images are performed by two separate modules. The loaded image at 1:1 zoom level is still in bayer format, and cannot be displayed correctly.
For that you need to add a "RAW developer" layer above the "RAW loader", where you will be able to tweak all typical RAW parameters (WB, exposure, output color...). Details are explained here: http://photoflowblog.blogspot.fr/2014/09/tutorial-how-to-process-raw-image-in.html

The reason for splitting the loading and the processing of RAW files is to be able to easily create "presets" that are independent from the loaded image. For example, if you want to easily re-use a given set of RAW processing parameters, you can simply select the "RAW loader" layer and click on the "Save" button at the bottom of the layer list, and then save the file with a ".pfp" extension.
Next time you will want to use the same settings, you can clock on the "Load" button at the left of the "Save" one and select the previously saved ".pfp" file. 
This will restore the "RAW loader" layer pre-configured with the settings stored in the preset.

When pressing the "Zoom -" button, the preview image get generated from a scaled-down demosaiced version that is cached during the loading phase. A fast demosaicing method is used in this case, which is OK for showing the image at 1:2 or below, but not accurate for 1:1 viewing.

**Comment by aferrero2707** [comment]
Thais problem has been recently fixed. Now the RAW pixel data is shown as a grayscale image at 100% zoom level. Closing the issue for now.
