### ISSUE TITLE
Missing typography glyphs.

### ISSUE THREAD

**Issue by ni-code** [aferrero2707/PhotoFlow#180]
Appimage 0.2.8 downloaded from git.
OS: solus linux.

I was trying photoflow with the appimage provided, but it seems that there's a problem with the font-face. All I get is the missing character glyph. 

![screenshot from 2018-12-07 19-31-16](https://user-images.githubusercontent.com/10292929/49668915-811c1480-fa57-11e8-8d51-eb3e68d80afd.png)

**Comment by aferrero2707** [comment]
Could you please try the stable development builds from here: https://github.com/aferrero2707/PhotoFlow/releases/tag/continuous

The most recent one is https://github.com/aferrero2707/PhotoFlow/releases/download/continuous/PhotoFlow-git-stable-20181208_0856-26c2bc3a91877400de859d29e42599ff773a7281-x86_64.AppImage

**Comment by ni-code** [comment]
@aferrero2707, I tried the version you linked, and it works fine. Thanks.

**Comment by aferrero2707** [comment]
Great! I'm closing this, feel free to re-open in case you encounter the same problem in recent development versions.
