### ISSUE TITLE
Crash when selecting input source in a mask layer

### ISSUE THREAD

**Issue by phweyland** [aferrero2707/PhotoFlow#181]
Wanted to reuse the mask of the previous local contrast, invert it and set up a new local contrast
![image](https://user-images.githubusercontent.com/23012047/50019418-e2516400-ffd2-11e8-88b0-6c3cc264a9bd.png)

When I tick show mask, no mask appears.
When I untick show mask pf crashes.

I've run gdb, the behaviour is a bit different. Doesn't crash on untick show mask, but does when untick invert mask.

[PhotoFlow-01.txt](https://github.com/aferrero2707/PhotoFlow/files/2681213/PhotoFlow-01.txt)
[20181105_Agde_069.jpg.pfi.txt](https://github.com/aferrero2707/PhotoFlow/files/2681227/20181105_Agde_069.jpg.pfi.txt)

using today pf build. Let me know if you need anything else.

**Comment by phweyland** [comment]
This one is crashing when I open the pfi without gdb.

With gdb the file opens, but pf crashes when I uncheck show mask.
![image](https://user-images.githubusercontent.com/23012047/50027147-8941fa00-ffeb-11e8-9af7-f5d9d108cf1f.png)


[PhotoFlow-02.txt](https://github.com/aferrero2707/PhotoFlow/files/2681680/PhotoFlow-02.txt)

[20181105_Agde_069.jpg.pfi.txt](https://github.com/aferrero2707/PhotoFlow/files/2681682/20181105_Agde_069.jpg.pfi.txt)

**Comment by phweyland** [comment]
I've added the clone layer, set the "mask  sky" as input source, and set on "mask sea" the previous layer as input source.
When I check show mask nothing appears. But crashes when uncheck (I think it crashed on the second time I unchecked ....)

![image](https://user-images.githubusercontent.com/23012047/50050828-47f23d00-0106-11e9-8fe8-a548b21ff67b.png)
[PhotoFlow-03.txt](https://github.com/aferrero2707/PhotoFlow/files/2683311/PhotoFlow-03.txt)

**Comment by phweyland** [comment]
Great ! with clone layer that works ! :-) Thank you
However I had to delete the topmost contrast layer and build it following your method.
Maybe there was something wrong in my pfi. When I opened it the clone layer did appear on top. I've moved it on the bottom, but each time I leave and come back to mask view, the clone layer was back on top... like this:
![image](https://user-images.githubusercontent.com/23012047/50053240-d03a0780-0131-11e9-9c65-d523877a0594.png)
Thanks !

**Comment by aferrero2707** [comment]
I'm currently fixing the problem with the input source selection for mask layers... hopefully your initial idea will be working properly in a short while. Will let you know here before closing the issue.

**Comment by phweyland** [comment]
Thanks so much.
I don't know if that's related but opening this pfi is endless (seems to process several times).
In any case it's much faster to disable the group and each component, then enable the group and components one by one (I can share the raw if needed).
[20181105_Agde_069.jpg.pfi.txt](https://github.com/aferrero2707/PhotoFlow/files/2683651/20181105_Agde_069.jpg.pfi.txt)

**Comment by aferrero2707** [comment]
@phweyland bilateral blur is definitely not optimized, and in fact I am replacing it with the "guided filter" for RawTherapee. According to the literature, it provides better transitions between smooth areas and sharp edges, and moreover is is significantly faster...

The new "local contrast" tool is actually based on the guided filter.

**Comment by aferrero2707** [comment]
@phweyland I have just committed a fix of your initial issue (crash when selecting an input source for the invert tool). Pre-compiled packages should be available in less than one hour... could you please check if the new code works correctly for you as well?

Thanks!

**Comment by phweyland** [comment]
Yes, I can now set a previous mask in "invert layer" different than a "clone layer" without trouble when I enable/disable show mask.
Thanks!

**Comment by aferrero2707** [comment]
Closing issue, fixed with 94b681ba0cc4afa26a56eb57fc3b8bbed475456f.
