### ISSUE TITLE
PF crashes when monitor color profile doesn't exist any more

### ISSUE THREAD

**Issue by phweyland** [aferrero2707/PhotoFlow#183]
After having moved the corresponding folder pf started to crash when open whatever file type.
Backtrace:
[PhotoFlow-05.txt](https://github.com/aferrero2707/PhotoFlow/files/2753477/PhotoFlow-05.txt)

**Comment by aferrero2707** [comment]
Thanks! I must introduce a safe fallback and a warning message in this case... meanwhile, you should be able to fix the situation by manually editing the PhF configuration file and remove the line that contains the missing monitor profile...

The config file under windows can be found in
```
%LocalAppData%\photoflow\config\options
```

**Comment by phweyland** [comment]
Good to know !
I've just redefined the monitor profile in preference before opening an image and that did work.

**Comment by aferrero2707** [comment]
Should be fixed by 3795f6976c61edc78a793e39251e375623731a9e
The program now pops up an information dialog that warns the user that the display profile cannot be found, and then falls back to sRGB.

Could you please check and confirm before I close the issue?

Thanks!

**Comment by phweyland** [comment]
Made a try but was unsuccessful. Here is the backtrace:
[photoflow_bt.txt](https://github.com/aferrero2707/PhotoFlow/files/2874775/photoflow_bt.txt)

**Comment by aferrero2707** [comment]
@phweyland I just realized that there was a problem when building the Win64 package, so you likely tested and older version of the code. The win64 package corresponding to the git head is now available: https://github.com/aferrero2707/PhotoFlow/releases/download/continuous/photoflow-w64-20190218_1830-git-stable-5f101bf82b3d506e5acee73ca40a5af186a0151e.zip

Sorry for that!

**Comment by phweyland** [comment]
Good !
![image](https://user-images.githubusercontent.com/23012047/53039534-ae396a00-347f-11e9-8c62-0e2df42b6bd9.png)

**Comment by aferrero2707** [comment]
Great! Then I will close this one.

Thanks for the feedback!
