### ISSUE TITLE
PF hangs while trying to delete tone mapping layer

### ISSUE THREAD

**Issue by gadolf66** [aferrero2707/PhotoFlow#184]
I duplicated a tone mapping layer, made some adjustments and then tried to delete it.
I looked into the pfi file and the duplicated layer seems to have gone, but PF is hanging with CPU constantly around 30%.
PhotoFlow-git-stable-20190111_2204-907a4f1c4772c9a8549a448dc01cc2a3760c77fb-x86_64
Ubuntu 18.04
i3 / 12 GB ram

[20181109_Cahuzeres_221.zip](https://github.com/aferrero2707/PhotoFlow/files/2761812/20181109_Cahuzeres_221.zip)
Image: https://discuss.pixls.us/t/filmic-a-personal-view/9990/33?u=gadolf

**Comment by aferrero2707** [comment]
I also see hangs/crashes sometime when deleting layers, there is somewhere a nasty bug that I could not catch yet.

Is the hanging reproducible in your case?

**Comment by gadolf66** [comment]
I will close this issue because it doesn't has to do with the tone mapping layer, but with any layer that has a mask that points to a layer that was later deleted.
