### ISSUE TITLE
Relight: caching takes forever

### ISSUE THREAD

**Issue by gadolf66** [aferrero2707/PhotoFlow#193]
After some edits, caching does not stop, and prevents exporting the image. Eventually, after around some 10 minutes, caching stops and the export takes place.
While caching, I can continue editing, adding new modules or change the settings in already existent ones.
Version: HEAD-ab342
OS: Ubuntu 18.04
Computer: Dell Inspiron N4050 (Intel i3)
Embbeded graphics card: 00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)

**Comment by gadolf66** [comment]
Apparently, the culprit seems to be the relight module: after I add it, it begins caching in the pattern described above. If I delete it, caching quickly stops and the cpu gets to its normal usage.
Added "Relight" to the issue title

**Comment by gadolf66** [comment]
This can be closed since after the changes proposed in the new caching mechanism branch the issue no longer happens.

**Comment by aferrero2707** [comment]
I am about to merge the `new-caching` branch into stable, so this will be finally fixed...

Thanks!
