### ISSUE TITLE
CMake FindPackageHandleStandardArgs compile issue on OSX

### ISSUE THREAD

**Issue by dustinkerstein** [aferrero2707/PhotoFlow#194]
I'm trying to compile PhotoFlow in the `linear_gamma` branch on OSX and am running into this error:

```
CMake Error at /usr/local/Cellar/cmake/3.15.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find MACINTEGRATION (missing: MACINTEGRATION_LIBRARY
  MACINTEGRATION_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.15.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindMacIntegration.cmake:27 (find_package_handle_standard_args)
  CMakeLists.txt:158 (find_package)
```

Have you seen this before? Let me know if you have any ideas on how to get past it. Thanks!

**Comment by aferrero2707** [comment]
@dustinkerstein I am going through the issues, after some time spent on heavy coding...

The linear_gamma branch is obsolete (I will delete it soon, as it has been merged into stable).
Could you try compiling the stable branch, and see if the problem persists? In which case, I would need the full cmake log, if possible.

**Comment by dustinkerstein** [comment]
Thanks. I am able to compile the stable branch.
