### ISSUE TITLE
histogramm.cc no variable border_bottom

### ISSUE THREAD

**Issue by HJarausch** [aferrero2707/PhotoFlow#199]
The current GIT version fails to compile
#ifdef GTKMM_3
bool PF::HistogramArea::on_draw(const Cairo::RefPtr<Cairo::Context>& cr)
{
  int border_size = 2;
  Gtk::Allocation allocation = get_allocation();
  const int width = allocation.get_width() - border_size*2;
  const int height = allocation.get_height() - border_size - border_bottom;
======================================= >>> ^^^^^^^^^^^^^^  is unknown
  const int x0 = border_size;
  const int y0 = border_size;
#endif

**Comment by aferrero2707** [comment]
@HJarausch the compilation issue should be now fixed in the stable branch (commit b4f3ba15b50c2f04d177b18dd9bbeaa40a82d9ba).

Could you please confirm?

Thanks!

**Comment by HJarausch** [comment]
Yes, thanks!
