### ISSUE TITLE
Lower part of  the main GUIs not visualized on small monitor (13 inches) on Windows 10

### ISSUE THREAD

**Issue by SilvioGrosso** [aferrero2707/PhotoFlow#201]
Hello,

On Windows 10 with:
photoflow-w64-20191023_2016-git-stable-d646102fdbfc9a11ab7a22bda5fd4dff69f52498

The bottom part of the main GUIs is not visualized on my Notebook monitor (around 13.3 inches).

I have tried everything I could think of to solve this problem.
For instance:
- Try to resize the border of the GUIs by dragging them;
- double click on the top bar to force a "redraw" of the GUIs,
- click on the 3 buttons on the upper right (minimize etc).

My monitor pertaints to a notebook ASUS X302UJ:
https://www.asus.com/Laptops/X302UJ/
13.3" 16:9 HD (1366x768)/Full HD (1920x1080) 

Other GTK softwares do not show this problem on this small monitor: Gimp, Rawtherapee, Darktable etc. Only Rawtherapee is not completely perfect but not on such a scale as Photoflow.

Here is a screenshot (Windows 10):
![photoflow-guis](https://user-images.githubusercontent.com/33007383/67512301-c9a4e680-f698-11e9-833a-45d36ace3d59.jpg)

 Here are the settings I have applied for the tools (after restarting the application):
<img width="451" alt="photoflow_settings" src="https://user-images.githubusercontent.com/33007383/67512335-e4775b00-f698-11e9-95d3-9435da585637.png">

**Comment by aferrero2707** [comment]
@SilvioGrosso I have reduced the number of vertical tool icons, as this is the part of the UI that cannot be shrunk further. The window should now fit in your screen. I also need to reduce the vertical size of the image tabs, to gain some more vertical space...

Could you check the latest windows build from the stable branch?

**Comment by SilvioGrosso** [comment]
@aferrero2707 

In all truth, IMHO, there is no a real need to solve this issue because it is "my fault" using such a small monitor with a graphical application!

I have reported this problem only because other GTK (Gimp etc) softwares work fine on this same notebook as regards their GUIs
Having said that, with the latest Windows version (photoflow-w64-20191031_1335-git-stable-b4f3ba15b50c2f04d177b18dd9bbeaa40a82d9ba) the GUIs fits the screen as long as you open only the first image. Opening a second image etc increases the size of the GUIs and the bottom part is no longer available.

Here is a video with all my steps on Windows 10 where I even try to resize the GUIs to no avail:
https://www.dropbox.com/s/j6i112y0juczdzw/PHOTOFLOW-GUI.mp4?dl=0

**Comment by SilvioGrosso** [comment]
I have checked again some GTK graphical softwares to really make sure they fit into my tiny monitor (13.3 inches; Full HD).

In short, PhotoFlow main windows fits into the screen as long as you work with only one image. 
When you open more images their name takes an extra space in  the GUIs and its bottom part is no longer available. On Windows 10, if you try to work in this part of the GUIs you even open the "Start Center" Menu of Windows 10 because of this :-)

Here is short video where I compare PhotoFlow (latest stable version) with Gimp, Darktable, Rawtherapee (Windows 10 as usual):
https://www.dropbox.com/s/u0aie9v2ssp6hhk/GTK_GUIs_SMALL-DISPLAYS_13.3.mp4?dl=0

BTW, PhotoFlow GUIs does not fit on Kubuntu 19.10 too when I run it through VirtualBox. 
This occurs because the Asus monitor is always the same (13.3 inches) :-)

**Comment by aferrero2707** [comment]
@SilvioGrosso could you please give me a short update on this issue? Is the situation better with the latest UI layout, or is the required minimal vertical space still too much for your screen?

Thanks!

**Comment by SilvioGrosso** [comment]
Just tested the latest build (PhotoFlow_git_v0.3.0-rc1_w64_20200122_1844_c51c4) on Windows 10 on my *usual* Asus notebook
So far nothing to complain about the GUIs :-)
The bottom part of the tools (dustbin) is better handled now on my small screen.

**Comment by aferrero2707** [comment]
I am closing this for the moment, please feel free to re-open in case the UI becomes unusable again on small screens.

Thanks!
