### ISSUE TITLE
Photoflow crashes while opening and closing more images (Kubuntu 19.10)

### ISSUE THREAD

**Issue by SilvioGrosso** [aferrero2707/PhotoFlow#202]
Hello,

Just installed PhotoFlow on Kubuntu 19.10 - KDE Desktop. 
It is a Virtual Box machine (Windows 10 - 64 bit is the host) with 4 Gb of Ram and an Intel 7 CPU
I have downloaded yesterday's latest AppImage (25 october) to run PhotoFlow

Photoflow always crashes while opening more images and closing one of them no matter what images I try: nef, jpeg etc

You can download a ZIP with 2 different log files where I have recorded all the outputs from the shell.
Beware: there is also a png image with a different bug: quite often Photoflow does not show the image which has been opened. The windows remains black, that is empty, even though the image has been somewhat opened.

https://www.dropbox.com/s/sjk8g7c7gyyt6fa/PHOTOFLOW_CRASH_CLOSE_IMAGES.zip?dl=0

**Comment by aferrero2707** [comment]
The commit aea7072b2a152187674d90df4c2632b8e82e1470  in the stable branch should fix the issue.

@SilvioGrosso Could you please check the latest stable appimage?
Thanks!

**Comment by SilvioGrosso** [comment]
Hello @aferrero2707 

Sure! I am going to test it on my Virtual machine (Kubuntu 19.10 - KDE desktop).

I have already tried the most recent stable release on Windows 10 but on this system I have got no crash when closing more images. 
It occured quite a lot in the past but now I can not reproduce this same crash.

Btw, I am a bit puzzled about the "correct" download to pick for Windows 10 (64 bit) because they all have a pretty similar name and are released on the same date.
Here is the 3 Zip files which look similar to me:

![photoflow-git](https://user-images.githubusercontent.com/33007383/67633664-d3a23180-f8b2-11e9-93b0-92850ab5fa9a.jpg)

**Comment by SilvioGrosso** [comment]
Hello @aferrero2707 

Just tested the new AppImage (Kubuntu 19.10):
https://github.com/aferrero2707/PhotoFlow/releases/download/continuous/PhotoFlow-git-stable-20191026_2035-aea7072b2a152187674d90df4c2632b8e82e1470-x86_64.AppImage

There are so many files and it is *extremely* confusing to pick the right one...

Unfortunately the crash is still there. I am sorry about that...
It really takes a lot of opening and closing the images but sooner or later it reappears :-(
This bug - crash has been present since I have started testing Photoflow over the years. Sooner or later, it always reappers (in the past it was a nightmare on Windows 10..).

As usual, once in while, completely on random, some images are not available. The window is black even though it looks like they are indeed opened. It occurs completely on random hence it is unpredictable which image will not "imported" correctly. All these same images work fine with Rawtherapee.

Here is a video with all my steps:
https://www.dropbox.com/s/llpn6y91tz7s9cu/PHOTOFLOW_CRASH-APP-IMAGE-27-oct-2019.mp4?dl=0

Here is the log with the ouput from the Linux shell:
https://www.dropbox.com/s/kmy0jpfszgw28gk/LOG_APPIMAGE_27-october.txt?dl=0

**Comment by SilvioGrosso** [comment]
Here is the ouput with another crash from gdb:
    Starting program: /home/silvio/Downloads/PhotoFlow-git-stable-20191026_2035-
    aea7072b2a152187674d90df4c2632b8e82e1470-x86_64.AppImage 
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    [Detaching after fork from child process 4303]
    process 4299 is executing new program: /usr/bin/env
    process 4299 is executing new program: /usr/bin/bash
    [Detaching after fork from child process 4308]
    [Detaching after fork from child process 4310]
    [Detaching after fork from child process 4311]
    [Detaching after fork from child process 4312]
    [Detaching after fork from child process 4313]
    [Detaching after fork from child process 4314]
    [Detaching after fork from child process 4315]
    [Detaching after fork from child process 4319]
    [Detaching after fork from child process 4322]
    [Detaching after fork from child process 4326]
    [Detaching after fork from child process 4332]
    [Detaching after fork from child process 4338]
    [Detaching after fork from child process 4343]
    [Detaching after fork from child process 4347]
    [Detaching after fork from child process 4348]
    [Detaching after fork from child process 4353]
    [Detaching after fork from child process 4356]
    [Detaching after fork from child process 4357]
    [Detaching after fork from child process 4361]
    [Detaching after fork from child process 4365]
    [Detaching after fork from child process 4366]
    [Detaching after fork from child process 4370]
    [Detaching after fork from child process 4375]
    [Detaching after fork from child process 4376]
    [Detaching after fork from child process 4381]
    [Detaching after fork from child process 4384]
    [Detaching after fork from child process 4385]
    [Detaching after fork from child process 4389]
    [Detaching after fork from child process 4393]
    [Detaching after fork from child process 4394]
    [Detaching after fork from child process 4398]
    [Detaching after fork from child process 4403]
    [Detaching after fork from child process 4404]
    [Detaching after fork from child process 4405]
    [Detaching after fork from child process 4412]
    [Inferior 1 (process 4299) exited with code 0213]

To use Gdb I follow these steps:
gdb ./Photoflow.....
set pagination off
set logging file "name-file.txt"
set logging on
run
#When the crash occurs
thread apply all bt full
quit

p.s: maybe there are better ways to deploy gdb as regards the logs about these crashes?

**Comment by SilvioGrosso** [comment]
The good news is that on Windows 10 (64 bit) no crash occurs.!

You can open no matter what images (NEF, DNG, RAF etc) and close them without problems. They even open reasonably fast. Not as fast as Rawtherapee but it is overall good.
Tested on:
PhotoFlow HEAD-98caa (2019-10-25), that is
photoflow-w64-20191025_1532-git-enhanced-usm-98caa8232b35e5d577b850e66a4702c8837ec82d

**Comment by aferrero2707** [comment]
Hopefully some good news on this. I have just pushed to the stable branch an additional fix for the crash when closing tabs. I tested the code on MacOS and Linux and I could not trigger any crash, except when closing an image that is still being processed ( I am working to fix this as well).

Could you please check the latest AppImage package once it will be available (the build is ongoing at the moment)?

Thanks!

**Comment by SilvioGrosso** [comment]
With the stable AppImage: 20191029_2321-4632257ab38f274995e56e49503417164402a88e-x86_64.
124 Mb, everything works much better!

I have tried to open many Raw images from Sony, Canon, Nikon and also some Dng images from smartphones.

It only crashed once BUT I think this is much more related to the fact that I am running PhotoFlow in a Virtual Machine with only 4 Gb of Ram (the host is Windows 10; the Guest is Kubuntu 19.10 with the AppImage).

In only one single occasion one single Raw image was not imported. 
Its window remained black even after waiting a lot of time (I have already reported this glitch). 
The same Raw image was imported fine later when I have closed it and reopened once again.

All in all, this build works extremely fine on Kubuntu - Kde Desktop (especially since this is a Virtual machine).
On Windows 10, strangely enough, I don't have any problem while opening-closing the same Raw images. In the past, on the contrary, this bug was quite frequent on this system too.

As you know, the crash occurring while closing and opening image has been present since the very first version of PhotoFlow, some years ago.
If I may crack a joke I would say it is one of its "features". Sometimes it disappears but later on it is very likely to surface again :-)

**Comment by aferrero2707** [comment]
Let's hope this bug is fixed once for all! I had to substantially modify the logic that deletes the images, now it is much cleaner.

Concerning the remaining crashes, 4GB of RAM should not be a problem at all.
I also observe the black image bug from time to time, but I could not look into it in detail yet.

I am closing this for now, please feel free to re-open the issue in case closing tabs crashes the application again.

Thanks!

EDIT: for reference, this was fixed in commit 1e812374e1e30139b30079629a9f7edab02feeaf

**Comment by SilvioGrosso** [comment]
Hello @aferrero2707 

As you proposed, I open this issue once again because the crash is still alive and kicking, unfortunately....
In all truth, now it looks even much worse than in the past.
I have tried twice the whole procedure (open and closing) and in both cases PhotoFlow always crashed pretty soon.
As usual, it suffices to open some Raw images (Canon, Nikon, Sony) and close some of them.
Tested on Kubuntu 19.10 - KDE desktop (as usual with a virtual Machine: Host is Windows 10).
Tested the AppImage Enhanced usm (30 october 2019)..."  BUT I do not know whether this release already contains your latest changes?

Here is a video with all my steps. At its very beginning you can still see the previous crash printed in the shell:
https://www.dropbox.com/s/4cohieqnt5435e7/PHOTOFLOW_CRASH-AGAIN.mp4?dl=0

On Windows 10, as usual the build is rock-solid. 
I have tested this build: photoflow-w64-20191031_1335-git-stable-b4f3ba15b50c2f04d177b18dd9bbeaa40a82d9ba
It is a bit surprising because on the forum Pixs.us I am often suggested to switch to Linux since it is a much better platform to work with Graphics applications :-) :-)
In all truth, as of today, in many years of testing, I have never experienced a single crash of Windows 10 whereas the Linux desktops (Unity, Kde) have subjected me to countless crashes...
And please, do not get me wrong, because I DO believe Linux is a wonderful system to work with :-)

**Comment by aferrero2707** [comment]
The fix is not yet in the enhanced-usm branch. Give me a little bit of time, and I will merge the changes there as well...

**Comment by SilvioGrosso** [comment]
Yep, I have imagined that...No need to rush! :-)

    Il giovedì 31 ottobre 2019, 21:35:14 CET, aferrero2707 <notifications@github.com> ha scritto:  
 
 
Reopened #202.

**Comment by aferrero2707** [comment]
On the other hand, the stable branch is OK on Linux as well, right?

**Comment by SilvioGrosso** [comment]
Yep. It looks stable. 
No crash whatsoever while opening and closing the Raw images (kubuntu 19.10).
Previously, I have selected the wrong AppImage (USM enhance) because It looked like it was the newest one...

**Comment by aferrero2707** [comment]
I am closing this again since the last reported issue with closing tabs is not related to the stable branch.
