### ISSUE TITLE
PhotoFlow doesn't build with recent vips releases

### ISSUE THREAD

**Issue by alexdupre** [aferrero2707/PhotoFlow#206]
Many calls to `vips_image_get_blob` fail because the signature of the third parameter changed from `void **` to `const void **`:

```error: no matching function for call to 'vips_image_get_blob'
    if( vips_image_get_blob( parents[i], "pf-image-hierarchy", (void**)&parray, &length) ) {
        ^~~~~~~~~~~~~~~~~~~
/usr/local/include/vips/header.h:203:5: note: candidate function not viable: no known conversion from 'void **' to 'const void **' for 3rd argument```

**Comment by aferrero2707** [comment]
@alexdupre I am working to fix this, I should be able to merge the new code in few hours.

**Comment by aferrero2707** [comment]
@alexdupre the compilation problem with recent VIPS versions should now be fixed in the stable branch. Could you please confirm?

Thanks!

**Comment by alexdupre** [comment]
I confirm it worked, thanks!
