### ISSUE TITLE
source tarball

### ISSUE THREAD

**Issue by alexmyczko** [aferrero2707/PhotoFlow#209]
it's huge, is all of src/external/ needed?

darktable
exiv2
lensfun
librtprocess
rawspeed

I already have these on my system:
```
ii  libexiv2-dev                                    0.27.2-3
ii  libexiv2-27:amd64                               0.27.2-3
ii  liblensfun-dev                                  0.3.2-4
ii  liblensfun1:amd64                               0.3.2-4
ii  liblensfun-data-v1                              0.3.2-4
```

indeed dropping lensfun+exiv2 almost halfens the source tarball (+.xz instead of .gz)
http://phd-sid.ethz.ch/debian/photoflow/test/

**Comment by aferrero2707** [comment]
I have those packages in the external folder for cases where the system-supplied versions are too old. However, I can modify the CMake configuration such that the corresponding sources are downloaded from the network instead of being bundled. Let me look into this...

**Comment by Piraty** [comment]
Distributions usually don't want to build the bundled libraries but link instead against system libs (exception is when you rely on patched version of them).
If you have restrictions on libraries' versions, you'd check for them in your CMakeLists.txt.

Most portable is to detect (find_package et al) system libs and fallback to src/external.

Also [v0.2.8.tar.gz](https://github.com/aferrero2707/PhotoFlow/archive/v0.2.8.tar.gz) currently has 8.8M (2.1M in src/external, extracted) which i don't consider much...

**Comment by aferrero2707** [comment]
@Piraty 
> Most portable is to detect (find_package et al) system libs and fallback to src/external.
This is what is being done for most of the external libraries, with the exception of RawSpeed which is always taken from `src/external`

**Comment by alexmyczko** [comment]
the main issue packaging software for debian (+ubuntu) is writing the debian/copyright file, in the worst case it can be this large:

https://metadata.ftp-master.debian.org/changelogs//main/c/colmap/colmap_3.6+dev2+git20191105-1_copyright

the less code, authors, files, licenses, the easier...

**Comment by Piraty** [comment]
i don't know about debian's tooling, but grabbing licenses (and ideally hashing the files to detect changes in new versions) is not the hard part here...

**Comment by alexmyczko** [comment]
> i don't know about debian's tooling, but grabbing licenses (and ideally hashing the files to detect changes in new versions) is not the hard part here...

true, writing the initial debian/copyright file, in a way it passes debian NEW queue, is the PITA,

**Comment by aferrero2707** [comment]
> true, writing the initial debian/copyright file, in a way it passes debian NEW queue, is the PITA,
@alexmyczko @Piraty 
Is there anything I can do to help? I am really not a debian package expert...

**Comment by alexmyczko** [comment]
no worries i am almost done missing cc-headache licenses and mit

**Comment by Piraty** [comment]
I can't tell you anything about debian, but in relation to this issue, i opened #212.
