### ISSUE TITLE
Batch mode not working

### ISSUE THREAD

**Issue by gotaalv** [aferrero2707/PhotoFlow#213]
Hello,
I've compiled on Linux (Mint 19.2) current release (a0d24). I'm using VIPS libvips 8.5.7 `from deb http://ppa.launchpad.net/dhor/myway/ubuntu bionic main` (Dariusz Duma <dhor@toxic.net.pl>)

I'm using this raw file: https://discuss.pixls.us/t/help-needed-to-showcase-photoflow-features-at-lgm2019/11722/10
The commands I have tested are:
+ ${PHOTOFLOW_BIN} --batch --config=size.pfp --export-opt=jpg_depth=8,jpg_compress=75 DSC_0230.NEF DSC_0230.jpeg
+ ${PHOTOFLOW_BIN} --batch --export-opt=jpg_depth=8,jpg_compress=75 DSC_0230.NEF DSC_0230.jpeg
+ ${PHOTOFLOW_BIN} --batch --config=my_presets.pfp DSC_0230.NEF DSC_0230.pfi

The error I get is `ERROR:/home/xxxxxxx/PhotoFlow-continuous/PhotoFlow/src/vips/tilecache_pf.c:159:phf_tile_pool_init: assertion failed: (_requested_number_of_tiles>0)`

Using this DEB (photoflow-git_2.9+git20190413-1460~ubuntu16.04.1_amd64.deb) from a DEB from PPA http://ppa.launchpad.net/dhor/myway works fine

KR,

**Comment by aferrero2707** [comment]
@gotaalv I confirm an issue with the batch processing. I am looking into it.

**Comment by aferrero2707** [comment]
@gotaalv the batch processing should be working again now in the stable branch, could you please confirm?

Thanks!

**Comment by gotaalv** [comment]
I confirm, it works!
Thanks
