### ISSUE TITLE
Compile 0.1.6 with GEXIV2

### ISSUE THREAD

**Issue by salvadhor** [aferrero2707/PhotoFlow#29]
I can't find what cause this issue - configure reports libgexiv2-dev as found, but further:

[ 11%] Building CXX object src/CMakeFiles/pfbase.dir/base/image.cc.o
cd /tmp/buildd/photoflow-0.1.6/obj-x86_64-linux-gnu/src && /usr/bin/x86_64-linux-gnu-g++    -DPF_HAS_LENSFUN -O3 -DNDEBUG -std=gnu++11 -Wno-error=narrowing -Dgmic_build -Dcimg_use_vt100 -Dgmic_is_parallel -Dcimg_use_fftw3 -Dcimg_use_tiff -Dcimg_use_zlib -Dcimg_display=0 -fno-ipa-sra -fpermissive -I/tmp/buildd/photoflow-0.1.6/src/dt -DLIBRAW_NODLL -DINSTALL_PREFIX='"/usr"'  -DLOCALEDIR="/usr/share/locale" -DGTKMM_3 -I/usr/include/gtkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gtkmm-3.0/include -I/usr/include/atkmm-1.6 -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-gnu/pangomm-1.4/include -I/usr/include/gtk-3.0 -I/usr/include/cairomm-1.0 -I/usr/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gdkmm-3.0/include -I/usr/include/atk-1.0 -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/gio-unix-2.0 -I/usr/include/harfbuzz -I/tmp/buildd/photoflow-0.1.150805/src/external -I/tmp/buildd/photoflow-0.1.6/src/external/LibRaw -I/usr/include/lensfun -I/usr/include/OpenEXR -I/usr/include/libxml2 -I/usr/include/libexif -I/usr/include/orc-0.4 -I/usr/include/libgsf-1 -I/usr/include/ImageMagick -I/usr/include/openslide -I/usr/include/x86_64-linux-gnu    -o CMakeFiles/pfbase.dir/base/image.cc.o -c /tmp/buildd/photoflow-0.1.6/src/base/image.cc
/tmp/buildd/photoflow-0.1.6/src/base/image.cc:33:29: fatal error: gexiv2-metadata.h: No such file or directory
 #include <gexiv2-metadata.h>

Looks like there's no -Igexiv2?

**Comment by aferrero2707** [comment]
Ohoops! It should be fixed now. Actually it seems that the pkg_config script for gexiv2 gives a different include path in the case of the official Ubuntu packages, compared with a custom installation...

My present fix will most likely break the building if gexiv2 is installed in some unusual place, but should now work in the case of the official packages.

I keep the issue opened as a reminder that I should find a better solution.

**Comment by aferrero2707** [comment]
No issues with building so far, closing.
