### ISSUE TITLE
After deleting layer, its parameters stay on right panel. 

### ISSUE THREAD

**Issue by salvadhor** [aferrero2707/PhotoFlow#30]
As topic says, version with new GUI (great work!).

**Comment by aferrero2707** [comment]
Whow, you are already testing it, I'm impressed! Thanks a lot for the feedback, I'll fix that before committing to the master branch.

So how do you find the new GUI layout? Is it more intuitive?

**Comment by salvadhor** [comment]
New GUI is very intuitive, sorts a lot of problems and create new ones :) But everything is more clear for now, I like idea of separate layers and its parameters.

**Comment by aferrero2707** [comment]
I've just noticed that you updated PhotoFlow's packages on your PPA from the latest "stable" branch. In fact, this code was not yet ready for production (although very close to that) as it still has some crashed and GUI "glitches".

Actually I think we have a small misunderstanding about the branching scheme I'm using on github. PhotoFlow repository contains three "main"branches:

- master: this is the branch that always holds the most up-to-date released version of the code. I'm not doing any development in the master branch, only committing the stable code when I consider it "production-ready". This guarantees that anyone cloning the master branch gets the most up-to-date stable code.

- stable: this is the branch in which I do the development for the next planned released. You can consider the stable branch as "good enough" to preview the new features and to do early bug reports (but several of the bugs might already be known to me and "work in progress"). However, the code is generally not yet good enough for packaging: as soon as it is ok, it will be immediately merged into the master branch and tagged with a new release number.

- develop: this is the branch where I keep the new "fancy" features that require too much work to be scheduled for the next release, and therefore should be kept out of the "stable" branch.


So, to cut it short, it is better to wait until new changes are merged into the "master" branch before updating the PPA, and always clone the master branch for this purpose. Usually I drop a small announcement on G+ and pixls.us as soon as the master branch is updated, so you can just keep an eye on either one or the other if that is easier for you...

Of course, nothing prevents anybody to test the code in the stable branch and give me feedback ;-)! Your recent suggestions are really useful and I'm already working on some of them...


Thanks a lot as usual, and sorry for the confusion!

**Comment by salvadhor** [comment]
Thanks for explanations.

**Comment by aferrero2707** [comment]
Fixed in stable branch.
