### ISSUE TITLE
Add "work in progress” indicator

### ISSUE THREAD

**Issue by salvadhor** [aferrero2707/PhotoFlow#33]
Small green/red indicator near zoom buttons would help to show that  Photoflow is generating preview/applying effect.

**Comment by aferrero2707** [comment]
You are definitely right, and this is now added in my TODO list... what I foresee:

1/ green "LED": preview is updated and processing engine is idle
2/ red "LED": preview is being updated
3/ orange "LED": preview is updated, but there is some background caching still ongoing, so one can expect the preview to be slower than usual

**Comment by aferrero2707** [comment]
Implemented in current stable branch.
