### ISSUE TITLE
Clicking on opacity/mask field next to Layer name

### ISSUE THREAD

**Issue by salvadhor** [aferrero2707/PhotoFlow#39]
Clicking on opacity/mask field next to layer name adds each time another tab, and another. Shouldn't it activate existing opacity/mask for current layer?

**Comment by aferrero2707** [comment]
You are right, I'll try to fix that before 0.2.1 is released.

**Comment by aferrero2707** [comment]
Fixed in stable branch: https://github.com/aferrero2707/PhotoFlow/commit/f7ec7a8ca343b38dc0ced56ea1d5091c8208effa. The behaviour is now exactly the expected one: if the tab is already existing it gets activated instead of adding a new one.

Thanks for reporting this!
