### ISSUE TITLE
RAW Developer tabs not fully visible

### ISSUE THREAD

**Issue by paynekj** [aferrero2707/PhotoFlow#42]
Using 0.2.1 on Windows 7 the right-hand tab (are there more than 4 tabs?) of the RAW Developer options is not fully visible

![untitled](https://cloud.githubusercontent.com/assets/11903737/10220296/12ec80ac-683e-11e5-9490-39354b94d994.png)

**Comment by aferrero2707** [comment]
Thanks, this is definitely something I'll need to fix in next release. I will most likely replace the text in the tabs with icons+tooltips.

By the way, fortunately there are only 4 tabs so nothing is really "lost".

**Comment by aferrero2707** [comment]
Fixed by shorter labels in latest version.
