### ISSUE TITLE
Problem with 0.2.3 build

### ISSUE THREAD

**Issue by salvadhor** [aferrero2707/PhotoFlow#50]
[ 81%] Building CXX object src/CMakeFiles/pfbase.dir/operations/impulse_nr.cc.o
cd /«PKGBUILDDIR»/obj-i686-linux-gnu/src && /usr/bin/i686-linux-gnu-g++    -DPF_HAS_LENSFUN -O3 -DNDEBUG -std=gnu++11 -Wno-error=narrowing -Dgmic_build -Dcimg_use_vt100 -Dgmic_is_parallel -Dcimg_use_fftw3 -Dcimg_use_tiff -Dcimg_use_zlib -Dcimg_display=0 -fno-ipa-sra -fpermissive -I/«PKGBUILDDIR»/src/dt -DLIBRAW_NODLL -DINSTALL_PREFIX='"/usr"'  -DLOCALEDIR="/usr/share/locale" -DGTKMM_2  -Wno-unused-parameter -I/usr/include/gtkmm-2.4 -I/usr/lib/i386-linux-gnu/gtkmm-2.4/include -I/usr/include/atkmm-1.6 -I/usr/include/giomm-2.4 -I/usr/lib/i386-linux-gnu/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/i386-linux-gnu/pangomm-1.4/include -I/usr/include/gtk-2.0 -I/usr/include/gtk-unix-print-2.0 -I/usr/include/gdkmm-2.4 -I/usr/lib/i386-linux-gnu/gdkmm-2.4/include -I/usr/include/atk-1.0 -I/usr/include/glibmm-2.4 -I/usr/lib/i386-linux-gnu/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib/i386-linux-gnu/glib-2.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/i386-linux-gnu/sigc++-2.0/include -I/usr/include/cairomm-1.0 -I/usr/lib/i386-linux-gnu/cairomm-1.0/include -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/lib/i386-linux-gnu/gtk-2.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0 -I/usr/include/harfbuzz -I/«PKGBUILDDIR»/src/external -I/«PKGBUILDDIR»/src/external/LibRaw -I/usr/include/lensfun -I/usr/include/OpenEXR -I/usr/include/libxml2 -I/usr/include/libexif -I/usr/include/orc-0.4 -I/usr/include/libgsf-1 -I/usr/include/ImageMagick -I/usr/include/openslide -I/usr/include/i386-linux-gnu    -o CMakeFiles/pfbase.dir/operations/impulse_nr.cc.o -c /«PKGBUILDDIR»/src/operations/impulse_nr.cc
In file included from /«PKGBUILDDIR»/src/operations/impulse_nr.cc:36:0:
/«PKGBUILDDIR»/src/operations/impulse_nr.hh: In member function 'void PF::ImpulseNR_RTAlgo_Proc<T, BLENDER, (PF::colorspace_t)2u, CHMIN, CHMAX, has_imap, has_omap, PREVIEW>::render(VipsRegion**, int, int, VipsRegion*, VipsRegion*, VipsRegion*, PF::OpParBase*)':
/«PKGBUILDDIR»/src/operations/impulse_nr.hh:174:49: warning: there are no arguments to 'memset' that depend on a template parameter, so a declaration of 'memset' must be available [-fpermissive]
       memset (impish[i], 0, iwidth*sizeof(float));

(...)

/«PKGBUILDDIR»/src/operations/impulse_nr.cc:173:1:   required from here
/«PKGBUILDDIR»/src/operations/impulse_nr.hh:174:49: error: 'memset' was not declared in this scope
/«PKGBUILDDIR»/src/operations/impulse_nr.hh: In instantiation of 'void PF::ImpulseNR_RTAlgo_Proc<T, BLENDER, (PF::colorspace_t)2u, CHMIN, CHMAX, has_imap, has_omap, PREVIEW>::render(VipsRegion**, int, int, VipsRegion*, VipsRegion*, VipsRegion*, PF::OpParBase*) [with T = float; BLENDER = PF::Blender<float, (PF::colorspace_t)2u, 0, 2, true>; int CHMIN = 0; int CHMAX = 2; bool has_imap = true; bool has_omap = true; bool PREVIEW = true; VipsRegion = _VipsRegion]':
/«PKGBUILDDIR»/src/operations/../base/processor.hh:229:7:   required from 'void PF::Processor<OPPAR, OP>::process(VipsRegion**, int, int, VipsRegion*, VipsRegion*, VipsRegion*) [with OPPAR = PF::ImpulseNR_RTAlgo_Par; OP = PF::ImpulseNR_RTAlgo_Proc; VipsRegion = _VipsRegion]'
/«PKGBUILDDIR»/src/operations/impulse_nr.cc:173:1:   required from here
/«PKGBUILDDIR»/src/operations/impulse_nr.hh:174:49: error: 'memset' was not declared in this scope
make[4]: *** [src/CMakeFiles/pfbase.dir/operations/impulse_nr.cc.o] Error 1

Full log here:

https://launchpadlibrarian.net/222906761/buildlog_ubuntu-trusty-i386.photoflow_0.2.3-1dhor~trusty_BUILDING.txt.gz

**Comment by aferrero2707** [comment]
Ooops! Added proper header file inclusion in master branch, it should compile fine now...

**Comment by aferrero2707** [comment]
Marking issue as fixed and closing.
