### ISSUE TITLE
Problem autobuild - after switch to rawspeed?

### ISSUE THREAD

**Issue by salvadhor** [aferrero2707/PhotoFlow#57]
Since rawspeed is bundled with PhotoFlow (am I right?), there should be no new dependencies. But autocompile (photoflow-git) fails with error:

In file included from /«BUILDDIR»/photoflow-git-2.4+git20151213/src/external/rawspeed/RawSpeed/CameraSensorInfo.cpp:1:0:
/«BUILDDIR»/photoflow-git-2.4+git20151213/src/external/rawspeed/RawSpeed/StdAfx.h:103:23: fatal error: pugixml.hpp: No such file or directory
 #include "pugixml.hpp"

**Comment by aferrero2707** [comment]
Yes, pugixml should be added as a dependency. I've also dropped you a
message on g+ about that... can this be easily fixed in both stable and got
packages? Thanks!
Il 14/dic/2015 15:11, "salvadhor" <notifications@github.com> ha scritto:

**Comment by salvadhor** [comment]
Ok, no problem.
