### ISSUE TITLE
Image rendering issues with RawSpeed

### ISSUE THREAD

**Issue by Joermungand** [aferrero2707/PhotoFlow#58]
It looks like there is an issue with the way raw photos are rendered after the move to RawSpeed. They get an extra black margin, as well as some artefacts along the top (or bottom) margin, as shown in the attached screenshots (the master-branch ones (first two) are taken with the master version, while the rawspeed ones (last two) are taken with the latest git from the stable branch; the ones marked detail are just of the top left corner in 1:1 zooming factor).

![master-branch](https://cloud.githubusercontent.com/assets/11301958/11790484/c202234e-a2a4-11e5-918e-ba7ab281e563.png)
![master-branch-detail](https://cloud.githubusercontent.com/assets/11301958/11790483/c2020102-a2a4-11e5-9bac-79ed51b6c516.png)
![rawspeed](https://cloud.githubusercontent.com/assets/11301958/11790485/c208dea0-a2a4-11e5-9c57-d97470666240.png)
![rawspeed-detail](https://cloud.githubusercontent.com/assets/11301958/11790486/c20bf5ea-a2a4-11e5-856d-f68c3e447760.png)

**Comment by aferrero2707** [comment]
Thanks! It should be fixed in the stable branch. I had to include for this the RAW cropping geometry given by RawSpeed, which in some cases is different from the one given by LibRAW.

**Comment by Joermungand** [comment]
Yeah, works fine now. Thanks.
