### ISSUE TITLE
missing windows 0.2.5 build

### ISSUE THREAD

**Issue by FredThompsonII** [aferrero2707/PhotoFlow#60]
Is there a 0.2.5 build for Windows? There is no link on the releases page. I modified the 0.2.4 link to use 0.2.5 and got a 404 (no such page) response.

**Comment by aferrero2707** [comment]
Not yet, I have still some compilation issue to solve... latest windows
release is 0.2.4, but I should have a 0.2.5 installer in the next couple of
days. I'll drop a message here as soon as it is done.
Il 30/dic/2015 00:15, "FredThompsonII" <notifications@github.com> ha
scritto:

**Comment by aferrero2707** [comment]
By the way, to get the 0.2.4 installer you have to go to the corresponding
release page:
https://github.com/aferrero2707/PhotoFlow/releases/tag/v0.2.4
Il 30/dic/2015 00:15, "FredThompsonII" <notifications@github.com> ha
scritto:

**Comment by aferrero2707** [comment]
Update: the windows installer for the 0.2.5 release is finally available! 
See here: https://github.com/aferrero2707/PhotoFlow/releases/tag/v0.2.5

**Comment by FredThompsonII** [comment]
On 1/3/2016 5:27 PM, aferrero2707 wrote:
>
> Update: the windows installer for the 0.2.5 release is finally available!
> See here: https://github.com/aferrero2707/PhotoFlow/releases/tag/v0.2.5
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/aferrero2707/PhotoFlow/issues/60#issuecomment-168546615>.
>

Thanks.

I'll start playing with it. FWIW, Pat David's website is how I found 
Photoflow.

-- 
   -=*=-

   Fred Thompson

   utils@mindspring.com
