### ISSUE TITLE
OSX Build - Stable Branch GIMP/Gegl Errors

### ISSUE THREAD

**Issue by Partha1b** [aferrero2707/PhotoFlow#62]
I am having the following error building on a Mac:

`/Users/partha/projects/src/gimp/plug-ins/Useful-Plugins/PhotoFlow/src/plugin/pfgimp.cc:372:9: error: taking the address of a temporary object of type
      'GeglRectangle' (aka '_GeglRectangle') [-Waddress-of-temporary]
        GEGL_RECTANGLE(0, 0, width, height),
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`
and
`/Users/partha/projects/src/gimp/plug-ins/Useful-Plugins/PhotoFlow/src/plugin/pfgimp.cc:396:21: error: no matching function for call to
      'gimp_parasite_new'
    exif_parasite = gimp_parasite_new("exif-data",
                    ^~~~~~~~~~~~~~~~~
`

My details:
<verbatim>
clang --version
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
</verbatim>

**Comment by aferrero2707** [comment]
Hi!

Both compilation issues should be fixed in current stable branch (see commit https://github.com/aferrero2707/PhotoFlow/commit/25055a65ae45687b333ad549147bb7fe102015b5).

**Comment by Partha1b** [comment]
Cool. It wasn't fixed last night. :)

Thanks!

**Comment by aferrero2707** [comment]
You are welcome, I actually fixed it on the fly after your message...

May I ask if you are planning to include photoflow (and the gimp plug-in) in your set of windows and OSX packages?

**Comment by Partha1b** [comment]
Elle Stone contacted me and asked me if I'd look into it and so I started
looking at PhotFlow. I was not familiar with your package.

If you have no objections, I would be happy to do it.

**Comment by aferrero2707** [comment]
On the contrary, I would be more than thankful!

I've been able so far to provide my own OSX and windows packages, but:

* the windows version is cross-compiled with mingw under linux, so probably not optimized at its best
* I have not yet managed to provide packages for the GIMP plug-in, and I'm not sure how to do that.

**Comment by Partha1b** [comment]
Thanks! I will definitely help out anyway I can. I build natively on
Windows and OSX by compiling and optimizing each build and dependencies
almost identically.

I host my own website and so would be happy to mirror you and provide my
builds of PhotFlow on my site.

**Comment by Partha1b** [comment]
Hi Andrea,

Finally had the time to upload all my builds. :) Includes your PF as the
default Raw editor.

Thanks,
Partha
