### ISSUE TITLE
Archlinux: problem installing stable branch

### ISSUE THREAD

**Issue by Joermungand** [aferrero2707/PhotoFlow#67]
The install script fails at line 72 in src/cmake_install.cmake, complaining about not being able to find the icc directory (I could see one in the linear_gamma branch, but not here). Is there an option I need to pass cmake to set the INSTALL_COMPONENT variable correctly?

**Comment by aferrero2707** [comment]
Ooops! I forgot to create the icc folder in the repository... it should be fixed now.

**Comment by Joermungand** [comment]
Thanks, I’ll recompile straight away, but I don’t think there should be any issue with the folder in place.

**Comment by aferrero2707** [comment]
Ok, so I will close the issue in a couple of days if I do not hear back from you...

Thanks!

**Comment by Joermungand** [comment]
I should be able to tell how it works in about half an hour or so, when it’s done compiling.

**Comment by Joermungand** [comment]
Build finished. All went fine. Thanks!
