### ISSUE TITLE
PhotoFlow WB Windows 64-bit

### ISSUE THREAD

**Issue by Partha1b** [aferrero2707/PhotoFlow#70]
PhotoFlow crashes on selecting spot WB.
1. Select image (see previous bug about RAW image files now showing)
2. Click on Raw developer
3. Click on WB
4. Select spot WB and click in image
5. Photoflow freezes (not responding)

**Comment by aferrero2707** [comment]
I have some idea about the reason for this freeze. I will try to add a path to the stable branch later today, and let you know when you can test it.

Thanks!

**Comment by aferrero2707** [comment]
I've updated the stable branch on github with a possible fix of the spot WB problem. However, I have no way to check it myself under windows, so I'll need to rely on your tests to confirm that the problem is fixed...

Thanks!

**Comment by Partha1b** [comment]
OK, that cured the "spot" WB. Then I tried the "color spot" and then it
crashed (not responding).

**Comment by aferrero2707** [comment]
That's already a good news! Can we declare the plugin "basically
functional"? I will disable the  color spot wb function until it is fixed.
Il 01/feb/2016 03:12, "Partha1b" <notifications@github.com> ha scritto:

**Comment by Partha1b** [comment]
OK Sounds good.

Did you update the stable branch?

**Comment by aferrero2707** [comment]
I just updated it.

**Comment by Partha1b** [comment]
OK thanks. I have another issue and will open that separately.
