### ISSUE TITLE
Build error on W32

### ISSUE THREAD

**Issue by gaaned92** [aferrero2707/PhotoFlow#72]
I am trying to make a  build on WIN32 with MSYS2 and GCC5.3.
I had some difficulties with vips but I thope they are solved.
Now I am building Photoflow  master branch  
with these parameters:
cmake -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$(pwd)/Release -DINSTALL_PREFIX=$(pwd)/Release 
  ../ make install

I get these errors
[ 15%] Building CXX object src/CMakeFiles/pfbase.dir/vips/lensfun.cc.obj
[ 16%] Building CXX object src/CMakeFiles/pfbase.dir/vips/perspective.cc.obj
In file included from E:/Phflsource/photoflow/src/vips/perspective.cc:56:0:
E:/Phflsource/photoflow/src/dt/iop/clipping.cc: In function 'void modify_roi_out(dt_iop_clipping_data_t_, dt_iop_roi_t_, const dt_iop_roi_t_)':
E:/Phflsource/photoflow/src/dt/iop/clipping.cc:155:37: warning: narrowing conversion of 'roi_in->dt_iop_roi_t::width' from 'int' to 'float' inside { } [-Wnarrowing]
   float corn_x[4] = { 0.0f, roi_in->width, roi_in->width, 0.0f };
                                     ^
E:/Phflsource/photoflow/src/dt/iop/clipping.cc:155:52: warning: narrowing conversion of 'roi_in->dt_iop_roi_t::width' from 'int' to 'float' inside { } [-Wnarrowing]
   float corn_x[4] = { 0.0f, roi_in->width, roi_in->width, 0.0f };
                                                    ^
E:/Phflsource/photoflow/src/dt/iop/clipping.cc:156:43: warning: narrowing conversion of 'roi_in->dt_iop_roi_t::height' from 'int' to 'float' inside { } [-Wnarrowing]
   float corn_y[4] = { 0.0f, 0.0f, roi_in->height, roi_in->height };
                                           ^
E:/Phflsource/photoflow/src/dt/iop/clipping.cc:156:59: warning: narrowing conversion of 'roi_in->dt_iop_roi_t::height' from 'int' to 'float' inside { } [-Wnarrowing]
   float corn_y[4] = { 0.0f, 0.0f, roi_in->height, roi_in->height };
                                                           ^
E:/Phflsource/photoflow/src/dt/iop/clipping.cc: In function 'void modify_roi_in(dt_iop_clipping_data_t_, const dt_iop_roi_t_, dt_iop_roi_t_, float, float)':
E:/Phflsource/photoflow/src/dt/iop/clipping.cc:284:65: error: narrowing conversion of '+Inf' from 'double' to 'float' inside { } [-Wnarrowing]
   float aabb_in[4] = { INFINITY, INFINITY, -INFINITY, -INFINITY };
                                                                 ^
E:/Phflsource/photoflow/src/dt/iop/clipping.cc:284:65: error: narrowing conversion of '+Inf' from 'double' to 'float' inside { } [-Wnarrowing]
E:/Phflsource/photoflow/src/dt/iop/clipping.cc:284:65: error: narrowing conversion of '-Inf' from 'double' to 'float' inside { } [-Wnarrowing]
E:/Phflsource/photoflow/src/dt/iop/clipping.cc:284:65: error: narrowing conversion of '-Inf' from 'double' to 'float' inside { } [-Wnarrowing]
src/CMakeFiles/pfbase.dir/build.make:734 : la recette pour la cible « src/CMakeFiles/pfbase.dir/vips/perspective.cc.obj » a échouée
make[2]: **\* [src/CMakeFiles/pfbase.dir/vips/perspective.cc.obj] Erreur 1
CMakeFiles/Makefile2:95 : la recette pour la cible « src/CMakeFiles/pfbase.dir/all » a échouée
make[1]: **\* [src/CMakeFiles/pfbase.dir/all] Erreur 2
Makefile:116 : la recette pour la cible « all » a échouée
make: **\* [all] Erreur 2

**Comment by aferrero2707** [comment]
I suggest you to build the stable branch instead of the master, at least until the next official version is released.

The problem you are reporting is already fixed in the stable branch.

The fact is that native compilation under windows is still under and therefore the fixes go into the stable branch, before being pushed to master when next version will be released. You will get a lot of other improvements from the stable branch as well.

**Comment by gaaned92** [comment]
Thank you. I will take stable branch.

**Comment by gaaned92** [comment]
@aferrero2707 
Build:
-stable branch on W32
-MSYS2/MINGW
- build made with msys
-GCC 5.3
The compilation step generates a lot of  warnings. I can upload a log if you want.
Building goes until final link where I get  errors that seem due to libvips, see [libvips.txt](https://github.com/aferrero2707/PhotoFlow/files/115884/libvips.txt)
During the libvips build, I got no error. The only thing I did was to define HOST=i686_PC_windows to permit translation of paths, else build aborts.  the ORC package is installed in MSYS2 with pacman.
Thank you for help

**Comment by aferrero2707** [comment]
I've added the search for ROC and OpenEXR in the cmake configuration for Windows, this should solve your building issue.

Could you drop a message here when/if it works?

Thanks!

**Comment by gaaned92** [comment]
Ok, now it builds. 
I included all required dlls from mingw .
Now I have to identify missing items like fonts, engines (it complains about murrine engine).

**Comment by aferrero2707** [comment]
Yes the murrine engine is needed by the gtk2 theme... let me know if you
need further help, I'll try to react as quickly as possible.

Thanks!
Il 04/feb/2016 16:22, "gaaned92" <notifications@github.com> ha scritto:
