### ISSUE TITLE
Since the 8 Feb. update photoflow crash with signal 11 upon any image closing

### ISSUE THREAD

**Issue by pmo-19** [aferrero2707/PhotoFlow#74]
As it looks like my e-mails from yesterday have been overlooked.
The Git version from yesterday and today crash with signal 11 caught from closing any open image.

~ImageEditor(): image deleted

(photoflow:13632): Gtk-CRITICAL **: IA__gtk_label_set_text: assertion 'GTK_IS_LABEL (label)' failed

(photoflow:13632): Gtk-CRITICAL **: IA__gtk_widget_queue_draw: assertion 'GTK_IS_WIDGET (widget)' failed
Error: signal 11:
photoflow(_Z7handleri+0x18)[0x657ff8]
/lib/x86_64-linux-gnu/libc.so.6(+0x36d40)[0x7f80ebfa2d40]
/usr/lib/x86_64-linux-gnu/libgtkmm-2.4.so.1(_ZN3Gtk8TreeView13get_selectionEv+0xc)[0x7f80eed100fc]
photoflow(_ZN2PF9LayerTree21get_selected_layer_idEv+0x25)[0x66f1e5]
photoflow(_ZN2PF11LayerWidget9update_cbEPS0_+0x45)[0x72b9b5]
/usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0(+0x1dce7)[0x7f80ed823ce7]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x135)[0x7f80ef9dace5]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x49048)[0x7f80ef9db048]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_loop_run+0x6a)[0x7f80ef9db30a]
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0(gtk_main+0xa7)[0x7f80ee2c0447]
memory: 54 allocations, 2153394 bytes
files: 0 open
memory: high-water mark 10.91 MB
$

**Comment by aferrero2707** [comment]
I confirm the crash, and today I have committed a fix that should solve this issue (see https://github.com/aferrero2707/PhotoFlow/commit/5b564e61ed0eae2d433304354c7c643d50f17660).

Could you confirm that things work correctly for you as well?

Thanks!

**Comment by pmo-19** [comment]
Yes as soon as my upload to Usenet is finished ...

**Comment by pmo-19** [comment]
Sorry, but this did not solve anything.
Beside that, there is convenience bug when I open an image and photoflow is not maximize. Right after I open another image. Right after I maximize photoflow the currently viewd image is maximized (ok) but when switch to the 1st opened image it is still minimized. And going min / maxi on photoflow won't change its behaviour as well. If I open a third image then the 3td is ok but the second will stay minimized ... The state maximize / minimize for the app is not seen as a global variable when viewing images ...

**Comment by pmo-19** [comment]
Today I made the update for the stable photoflow package and it looks like my adaptative patch is working. Both stable and unstable can be used at the time.
While testing their behaviour I can confirm that the crash on closing an image bug is quite ancient as it is as well in the stable version if you open more than one image. While in the unstable version the closing image bug appears with only one image open ... since last Monday Feb., 8th modifications. The unstable build from Feb. 7th did not crash with only one image, but probably behaved like the stable build 0.2.5 (quite old now).

**Comment by aferrero2707** [comment]
The remaining crash when closing image tabs was due to a missing return value from a GTK idle callback. This is hopefully finally solved in the current stable branch.

I will look into the other issues and suggestions during the next days.

**Comment by pmo-19** [comment]
OK. The crash bug is now corrected. Thanks.
However, the maximize / minmize still apply only to one image (the open image while performing maximize Photo Flow main window). I understand you will look at that later on.
Then in addition to the other "convenience" bugs, following a crash Photo Flow offers to recover the image (nice capability), but it then set the image as "changed" with a wildcard char '*' in its tab header and upon closing ask for saving the changes. That should not occur since the user didn't change anything. Photo Flow may only have restored its cache. This is the only change in cache which should not be deemed a change actually.

**Comment by pmo-19** [comment]
Another convenience would be to change the color of the button icons as black on black is visually poor. The ideal would be one set of icon for dark themes and one set for light themes. The switch may be made somewhere in the configuration.

**Comment by pmo-19** [comment]
And I will finish with one question: Where do you set the title name of the main window ? As I realize I will need to add a patch to change its name to Photo Flow Git or Photo Flow Unstable. Thanks.

**Comment by pmo-19** [comment]
New side effect bug following yesterday crash bug correction. The first time I open an image in Photo Flow (i.e. the first opened image) I get a small image. Either closing and reopening or closing altogether Photo Flow and relaunching it will open the image in full frame.

**Comment by pmo-19** [comment]
Another NOTE : I received today an e-mail proving ounce again you did intend to undercut what I do / or what I informed you about what I plan to add in my PPA.
I think that your continued plot with Mr. Duma + the latest development will lead me to leave your project and remove your Photo Flow from my PPA.

**Comment by aferrero2707** [comment]
pmo-19: concerning the bug in the preview image size, I'm aware of that and I'm still fighting with the GTK logic to properly fit the image to screen at program start-up. I plan to fix that once for all before next official release.

Concerning the email exchange you are mentioning in your last post, this is really not the place for such a discussion, because:

1. it has nothing to do with the bugs that are reported and followed in this issue
2. the rest of the readers don't have the least idea what we are talking about

Therefore I decided to remove the comment and I propose that we continue the discussion in a closed circle, like it was started.

**Comment by pmo-19** [comment]
@aferrero2707 I bet you were not aware of multiple tabs opening for the same source image though ?

**Comment by aferrero2707** [comment]
Most of the issues are fixed in stable branch.

The issue when opening the same image twice has been moved in a separate report.
