### ISSUE TITLE
About using pfgimp in Linux Ubuntu

### ISSUE THREAD

**Issue by pmo-19** [aferrero2707/PhotoFlow#75]
Anyone can provides information about how to add the pfgimp exec. within GIMP 2.9 ?
`$ ./pfgimp`
`./pfgimp is a GIMP plug-in and must be run by GIMP to be used`
However this is an exec. file and is not alike other plugins located in`/usr/share/gimp/2.0/` for Ubuntu.
Should I have to compile / build GIMP 2.9 ? However how to get pfgimp seen / run by GIMP ?

**Comment by aferrero2707** [comment]
The plug-in is for the moment only compatible with GIMP 2.9, and it only gets compiled if the GIMP 2.9 development libraries are found on the system.

To use it, you should copy the pfgimp executable to 

    $HOME/.config/GIMP/2.9/plug-ins/

Further information can be found [here](https://discuss.pixls.us/t/photoflow-as-a-gimp-plug-in-now-usable/681).

**Comment by pmo-19** [comment]
Sure, however there is a git build of the 2.9 version widely available as an Ubuntu PPA. And I intend to provide the plugin in my PPA.
So in order to use it I missed the location for plugins. It has been a while since I didn't use GIMP though.
Thanks for the details, I will try that ASAP.

**Comment by aferrero2707** [comment]
The photoflow gimp plug-in only work at the moment as a file loader, i.e. it gets automatically invoked whenever gimp attempts to open a RAW file. There is therefore no menu entry for it.

I am not sure if/how it could be possible to select between UFraw and PF...

AFAIK the global gimp plug-in folder is /usr/lib/gimp/2.0/plug-ins/
