### ISSUE TITLE
Icons missing for Open, Save, Save as

### ISSUE THREAD

**Issue by Joermungand** [aferrero2707/PhotoFlow#76]
Sorry to be a nag, but, after the latest commit in stable, the icons on the Open, Save, and Save as no longer show up.

**Comment by aferrero2707** [comment]
No problem... my fault, I wanted to improve the file handling icons and
forgot to commit the PNG files. Next commit should be OK.

Thanks!
Il 14/feb/2016 11:20, "Joermungand" <notifications@github.com> ha scritto:

**Comment by Joermungand** [comment]
Icons back in. Thanks.
