### ISSUE TITLE
G'MIC 1.6.9, latest patches and problems

### ISSUE THREAD

**Issue by salvadhor** [aferrero2707/PhotoFlow#77]
Latest set of patches breaks compile on Ubuntu (launchpad, photoflow-git):

[ 70%] Building CXX object src/CMakeFiles/pfbase.dir/vips/gmic/gmic/src/gmic.cpp.o
cd /«BUILDDIR»/photoflow-git-2.4+git20160221/obj-x86_64-linux-gnu/src && /usr/bin/x86_64-linux-gnu-g++    -DPF_HAS_LENSFUN -O3 -ffast-math -ftree-vectorize -DNDEBUG -std=gnu++11 -Wno-error=narrowing -Dgmic_build -Dcimg_use_vt100 -Dgmic_is_parallel -Dcimg_use_fftw3 -Dcimg_use_tiff -Dcimg_use_zlib -Dcimg_display=0 -fno-ipa-sra -fpermissive -I/«BUILDDIR»/photoflow-git-2.4+git20160221/src/dt -DLIBRAW_NODLL -DINSTALL_PREFIX='"/usr"'  -DLOCALEDIR="/usr/share/locale" -DBUNDLED_LENSFUN=1 -DGTKMM_2  -Wno-unused-parameter -fPIC -I/usr/include/gtkmm-2.4 -I/usr/lib/x86_64-linux-gnu/gtkmm-2.4/include -I/usr/include/atkmm-1.6 -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-gnu/pangomm-1.4/include -I/usr/include/gtk-2.0 -I/usr/include/gtk-unix-print-2.0 -I/usr/include/gdkmm-2.4 -I/usr/lib/x86_64-linux-gnu/gdkmm-2.4/include -I/usr/include/atk-1.0 -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/cairomm-1.0 -I/usr/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0 -I/usr/include/harfbuzz -I/«BUILDDIR»/photoflow-git-2.4+git20160221/src/external -I/«BUILDDIR»/photoflow-git-2.4+git20160221/src/external/LibRaw -I/usr/include/OpenEXR -I/usr/include/libxml2 -I/usr/include/libexif -I/usr/include/orc-0.4 -I/usr/include/libgsf-1 -I/usr/include/ImageMagick -I/usr/include/openslide -I/usr/include/x86_64-linux-gnu -I/«BUILDDIR»/photoflow-git-2.4+git20160221/obj-x86_64-linux-gnu/include    -o CMakeFiles/pfbase.dir/vips/gmic/gmic/src/gmic.cpp.o -c /«BUILDDIR»/photoflow-git-2.4+git20160221/src/vips/gmic/gmic/src/gmic.cpp
/«BUILDDIR»/photoflow-git-2.4+git20160221/src/vips/gmic/gmic/src/gmic.cpp: In member function 'gmic& gmic::_run(const cimg_library::CImgList<char>&, unsigned int&, cimg_library::CImgList<T>&, cimg_library::CImgList<char>&, cimg_library::CImgList<T>&, cimg_library::CImgList<char>&, const unsigned int*, bool*, const char*, const cimg_library::CImg<unsigned int>*)':
/«BUILDDIR»/photoflow-git-2.4+git20160221/src/vips/gmic/gmic/src/gmic.cpp:9281:17: error: 'wait_mode' was not declared in this scope
             if (wait_mode) {
                 ^
In file included from /«BUILDDIR»/photoflow-git-2.4+git20160221/src/vips/gmic/gmic/src/gmic.h:171:0,
                 from /«BUILDDIR»/photoflow-git-2.4+git20160221/src/vips/gmic/gmic/src/gmic.cpp:1912:
/«BUILDDIR»/photoflow-git-2.4+git20160221/src/vips/gmic/gmic/src/gmic.cpp:9282:25: error: '_threads_data' was not declared in this scope
               cimg_forY(_threads_data,l) if (_threads_data[l].is_thread_running) {
                         ^
/«BUILDDIR»/photoflow-git-2.4+git20160221/src/vips/gmic/gmic/src/./CImg.h:712:52: note: in definition of macro 'cimg_for1'
 #define cimg_for1(bound,i) for (int i = 0; i<(int)(bound); ++i)
                                                    ^
/«BUILDDIR»/photoflow-git-2.4+git20160221/src/vips/gmic/gmic/src/gmic.cpp:9282:15: note: in expansion of macro 'cimg_forY'
               cimg_forY(_threads_data,l) if (_threads_data[l].is_thread_running) {

**Comment by Joermungand** [comment]
Same here on 64-bit Arch.

**Comment by aferrero2707** [comment]
I will look into this issue later today, and let you know.

Thanks!

**Comment by aferrero2707** [comment]
The issue should be fixed in stable branch.

**Comment by Joermungand** [comment]
Affirmative! It builds. Thanks.

**Comment by salvadhor** [comment]
Yes, everything works now.
