### ISSUE TITLE
Display tears when image is larger than display viewer and scrollbars used.

### ISSUE THREAD

**Issue by grosgood** [aferrero2707/PhotoFlow#8]
Built from: 
commit 1d7c20e8ece8a5a6f042a886ffc2e73cd5502c2b
Author: Ferrero Andrea <aferrero1975@gmail.com>
Date:   Thu Nov 6 14:32:10 2014 +0100
Platform details:
Hardware: Dell Optiplex GX620 Minitower 
Display controller: Intel Corporation 82945G/GZ Integrated Graphics Controller (rev 02)
uname: Linux harriet 3.14.14-gentoo #1 SMP Sun Aug 10 19:53:42 EDT 2014 x86_64 Intel(R) Pentium(R) 4 CPU 2.80GHz GenuineIntel GNU/Linux
Kernel module: i915
Display driver: intel
X11 Server:  X.Org X Server 1.15.0
build configuration output:
 bash build.sh
rm: cannot remove ‘CMakeCache.txt’: No such file or directory
-- The C compiler identification is GNU 4.8.3
-- The CXX compiler identification is GNU 4.8.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- Check for LCMS2 availability...
-- checking for module 'lcms2'
--   found lcms2, version 2.6
-- Found TIFF: /usr/lib64/libtiff.so (found version "4.0.3") 
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.8") 
-- checking for module 'fftw3>=3.0'
--   found fftw3, version 3.3.3
-- checking for module 'sigc++-2.0'
--   found sigc++-2.0, version 2.3.1
-- checking for module 'vips>=7.40.11'
--   found vips, version 7.42.0
-- VIPS_INCLUDE_DIRS:         /usr/local/include/usr/include/libxml2/usr/include/ImageMagick-6/usr/include/orc-0.4/usr/include/OpenEXR/usr/include/pango-1.0/usr/include/harfbuzz/usr/include/pango-1.0/usr/include/glib-2.0/usr/lib64/glib-2.0/include/usr/include/freetype2/usr/include/libpng16/usr/include/libexif
-- VIPS_LIBRARY_DIRS:         /usr/local/lib
-- checking for module 'gtkmm-3.0'
--   found gtkmm-3.0, version 3.12.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gosgood/PhotoFlow/build
ldd output:
gosgood@harriet ~/PhotoFlow/build/Debug/bin $ ldd photoflow
	linux-vdso.so.1 (0x00007fff6ebff000)
	libsigc-2.0.so.0 => /usr/lib64/libsigc-2.0.so.0 (0x00007ff507570000)
	libgtkmm-3.0.so.1 => /usr/lib64/libgtkmm-3.0.so.1 (0x00007ff506cc1000)
	libatkmm-1.6.so.1 => /usr/lib64/libatkmm-1.6.so.1 (0x00007ff506a75000)
	libgdkmm-3.0.so.1 => /usr/lib64/libgdkmm-3.0.so.1 (0x00007ff5067ff000)
	libgiomm-2.4.so.1 => /usr/lib64/libgiomm-2.4.so.1 (0x00007ff50646d000)
	libpangomm-1.4.so.1 => /usr/lib64/libpangomm-1.4.so.1 (0x00007ff506240000)
	libglibmm-2.4.so.1 => /usr/lib64/libglibmm-2.4.so.1 (0x00007ff505fcd000)
	libgtk-3.so.0 => /usr/lib64/libgtk-3.so.0 (0x00007ff505939000)
	libgdk-3.so.0 => /usr/lib64/libgdk-3.so.0 (0x00007ff5056a9000)
	libpangocairo-1.0.so.0 => /usr/lib64/libpangocairo-1.0.so.0 (0x00007ff50549c000)
	libpango-1.0.so.0 => /usr/lib64/libpango-1.0.so.0 (0x00007ff505252000)
	libatk-1.0.so.0 => /usr/lib64/libatk-1.0.so.0 (0x00007ff50502c000)
	libcairo-gobject.so.2 => /usr/lib64/libcairo-gobject.so.2 (0x00007ff504e23000)
	libgio-2.0.so.0 => /usr/lib64/libgio-2.0.so.0 (0x00007ff504abf000)
	libcairomm-1.0.so.1 => /usr/lib64/libcairomm-1.0.so.1 (0x00007ff504899000)
	libcairo.so.2 => /usr/lib64/libcairo.so.2 (0x00007ff50458c000)
	libgdk_pixbuf-2.0.so.0 => /usr/lib64/libgdk_pixbuf-2.0.so.0 (0x00007ff50436b000)
	libgobject-2.0.so.0 => /usr/lib64/libgobject-2.0.so.0 (0x00007ff50411c000)
	libglib-2.0.so.0 => /usr/lib64/libglib-2.0.so.0 (0x00007ff503df2000)
	libtiff.so.5 => /usr/lib64/libtiff.so.5 (0x00007ff503b82000)
	liblcms2.so.2 => /usr/lib64/liblcms2.so.2 (0x00007ff50392c000)
	libvips.so.38 => /usr/local/lib64/libvips.so.38 (0x00007ff503310000)
	libMagickWand-6.Q32HDRI.so.2 => /usr/lib64/libMagickWand-6.Q32HDRI.so.2 (0x00007ff502ff0000)
	libMagickCore-6.Q32HDRI.so.2 => /usr/lib64/libMagickCore-6.Q32HDRI.so.2 (0x00007ff502b59000)
	libpng16.so.16 => /usr/lib64/libpng16.so.16 (0x00007ff502926000)
	libz.so.1 => /lib64/libz.so.1 (0x00007ff502710000)
	libjpeg.so.62 => /usr/lib64/libjpeg.so.62 (0x00007ff5024bb000)
	libgmodule-2.0.so.0 => /usr/lib64/libgmodule-2.0.so.0 (0x00007ff5022b7000)
	libxml2.so.2 => /usr/lib64/libxml2.so.2 (0x00007ff501f66000)
	libpangoft2-1.0.so.0 => /usr/lib64/libpangoft2-1.0.so.0 (0x00007ff501d52000)
	libfreetype.so.6 => /usr/lib64/libfreetype.so.6 (0x00007ff501ab0000)
	libfontconfig.so.1 => /usr/lib64/libfontconfig.so.1 (0x00007ff501876000)
	libfftw3.so.3 => /usr/lib64/libfftw3.so.3 (0x00007ff5014fb000)
	liborc-0.4.so.0 => /usr/lib64/liborc-0.4.so.0 (0x00007ff50127d000)
	libIlmImf.so.6 => /usr/lib64/libIlmImf.so.6 (0x00007ff500fb8000)
	libImath.so.6 => /usr/lib64/libImath.so.6 (0x00007ff500db1000)
	libHalf.so.6 => /usr/lib64/libHalf.so.6 (0x00007ff500b6e000)
	libIex.so.6 => /usr/lib64/libIex.so.6 (0x00007ff50094d000)
	libIlmThread.so.6 => /usr/lib64/libIlmThread.so.6 (0x00007ff500746000)
	libcfitsio.so.3 => /usr/lib64/libcfitsio.so.3 (0x00007ff50038f000)
	libm.so.6 => /lib64/libm.so.6 (0x00007ff500090000)
	libwebp.so.5 => /usr/lib64/libwebp.so.5 (0x00007ff4ffe34000)
	libexif.so.12 => /usr/lib64/libexif.so.12 (0x00007ff4ffbef000)
	libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.3/libstdc++.so.6 (0x00007ff4ff8ed000)
	libfftw3_threads.so.3 => /usr/lib64/libfftw3_threads.so.3 (0x00007ff4ff6e6000)
	libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.3/libgcc_s.so.1 (0x00007ff4ff4d0000)
	libc.so.6 => /lib64/libc.so.6 (0x00007ff4ff133000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff4fef15000)
	libX11.so.6 => /usr/lib64/libX11.so.6 (0x00007ff4febe1000)
	libXi.so.6 => /usr/lib64/libXi.so.6 (0x00007ff4fe9d1000)
	libXfixes.so.3 => /usr/lib64/libXfixes.so.3 (0x00007ff4fe7cb000)
	libatk-bridge-2.0.so.0 => /usr/lib64/libatk-bridge-2.0.so.0 (0x00007ff4fe59e000)
	libXrandr.so.2 => /usr/lib64/libXrandr.so.2 (0x00007ff4fe394000)
	libXcursor.so.1 => /usr/lib64/libXcursor.so.1 (0x00007ff4fe189000)
	libXcomposite.so.1 => /usr/lib64/libXcomposite.so.1 (0x00007ff4fdf86000)
	libXdamage.so.1 => /usr/lib64/libXdamage.so.1 (0x00007ff4fdd83000)
	libXext.so.6 => /usr/lib64/libXext.so.6 (0x00007ff4fdb71000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007ff4fd95a000)
	libpixman-1.so.0 => /usr/lib64/libpixman-1.so.0 (0x00007ff4fd6c2000)
	libEGL.so.1 => /usr/lib64/libEGL.so.1 (0x00007ff4fd4a4000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007ff4fd2a0000)
	libxcb-shm.so.0 => /usr/lib64/libxcb-shm.so.0 (0x00007ff4fd09d000)
	libxcb-render.so.0 => /usr/lib64/libxcb-render.so.0 (0x00007ff4fce93000)
	libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007ff4fcc73000)
	libXrender.so.1 => /usr/lib64/libXrender.so.1 (0x00007ff4fca69000)
	libGL.so.1 => /usr/lib64/libGL.so.1 (0x00007ff4fc80a000)
	librt.so.1 => /lib64/librt.so.1 (0x00007ff4fc602000)
	libffi.so.6 => /usr/lib64/libffi.so.6 (0x00007ff4fc3fa000)
	libgomp.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.3/libgomp.so.1 (0x00007ff4fc1ec000)
	liblqr-1.so.0 => /usr/lib64/liblqr-1.so.0 (0x00007ff4fbfdd000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007ff4fbdcd000)
	libltdl.so.7 => /usr/lib64/libltdl.so.7 (0x00007ff4fbbc3000)
	libharfbuzz.so.0 => /usr/lib64/libharfbuzz.so.0 (0x00007ff4fb969000)
	libexpat.so.1 => /usr/lib64/libexpat.so.1 (0x00007ff4fb73f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff507776000)
	libatspi.so.0 => /usr/lib64/libatspi.so.0 (0x00007ff4fb510000)
	libdbus-1.so.3 => /usr/lib64/libdbus-1.so.3 (0x00007ff4fb2d6000)
	libX11-xcb.so.1 => /usr/lib64/libX11-xcb.so.1 (0x00007ff4fb0d4000)
	libxcb-dri2.so.0 => /usr/lib64/libxcb-dri2.so.0 (0x00007ff4faecf000)
	libxcb-xfixes.so.0 => /usr/lib64/libxcb-xfixes.so.0 (0x00007ff4facc8000)
	libgbm.so.1 => /usr/lib64/libgbm.so.1 (0x00007ff4faac2000)
	libudev.so.1 => /lib64/libudev.so.1 (0x00007ff4fa8b0000)
	libdrm.so.2 => /usr/lib64/libdrm.so.2 (0x00007ff4fa6a4000)
	libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007ff4fa4a0000)
	libXdmcp.so.6 => /usr/lib64/libXdmcp.so.6 (0x00007ff4fa29a000)
	libglapi.so.0 => /usr/lib64/libglapi.so.0 (0x00007ff4fa073000)
	libxcb-glx.so.0 => /usr/lib64/libxcb-glx.so.0 (0x00007ff4f9e5a000)
	libXxf86vm.so.1 => /usr/lib64/libXxf86vm.so.1 (0x00007ff4f9c54000)
	libgraphite2.so.3 => /usr/lib64/libgraphite2.so.3 (0x00007ff4f9a36000)
Documentation at: https://backup.filesanywhere.com/fs/v.aspx?v=8c72658c5a6271b5a4ac
(link is good for 60 days. Will expire 05-January-2015 @ 15:35 EST (UTC-5))
Documentation synopsis:
1. Video:  tearingdemo.mp4 (3 min, 17 sec) shows effects of using scrollbars with an oversized image on this particular hardware platform and this particular build.
2. photoflowlogs - zipped text file of standard output to shell while program was running
3. brisbrane_nsw.jpg - image used while demonstrating bug.

**Comment by aferrero2707** [comment]
I have finally found and fixed the tearing and misbehavior with recent GTK 3.x libraries, so I think we can now close this issue.

The present git develop branch should compile and run correctly in any GTK 2.x or GTK 3.x environment.

The problem was more on my side than GTK one, specifically I was using 
    window->create_cairo_context()
to draw the image, instead of using the context directly provided by the on_draw() callback. This worked with earlier versions of GTK but not with more recent ones. I do not know if that's a kind of bug in GTK, however "doing things the right way" just works, so I'm not planning to dig that further.
