### ISSUE TITLE
.desktop file points to Darktable instead of PhotoFlow

### ISSUE THREAD

**Issue by Joermungand** [aferrero2707/PhotoFlow#86]
I was trying to adjust the AUR PKGUILD to reflect the latest commit in stable, and I noticed that all references in the .desktop file point to Darktable instead of PhotoFlow. Could have been easily solved by adding a sed line to the script, but I thought it should be done upstream:
```
[Desktop Entry]
Name=PhotoFlow
_GenericName=Virtual Lighttable and Darkroom
_Comment=Organize and develop images from digital cameras

X-GNOME-FullName=PhotoFlow Photo Workflow Software

Version=1.0

Type=Application
Categories=Graphics;Photography;GTK;
# TRANSLATORS: Search terms to find this application. Do NOT translate or localize the semicolons! The list MUST also end with a semicolon!
_Keywords=graphics;photography;raw;

Exec=photoflow %U
TryExec=photoflow
Terminal=false
StartupNotify=true

MimeType=application/x-photoflow;image/x-dcraw;image/jpeg;image/jpg;image/jp2;image/png;image/tiff;image/x-portable-pixmap;image/x-portable-floatmap;image/x-exr;

Icon=photoflow

X-Unity-IconBackgroundColor=#252525

```

**Comment by aferrero2707** [comment]
What a shame! I took the darktable desktop file as a starting point, but them forgot to commit the modified version... I'm doing that right now, thanks for noticing!

**Comment by aferrero2707** [comment]
Change committed.

**Comment by Joermungand** [comment]
Thanks! By the way, congrats on the icon! It turned out very well.

**Comment by aferrero2707** [comment]
The icon is actually not my own creation, but the great result of a sort-of collaborative effort in which very skilled people contributed!

here is the full story: https://discuss.pixls.us/t/help-needed-photoflow-application-icon-design/1014/73

**Comment by Joermungand** [comment]
Yes, I am aware of the story behind it; no reason to be any less proud 
of it though :).
