### ISSUE TITLE
Build error in src/operations/convert_colorspace.hh

### ISSUE THREAD

**Issue by Joermungand** [aferrero2707/PhotoFlow#89]
Package fails to build unless I replace `#include <string>` with `#include <cstring>` in src/operations/convert_colorspace.hh. It is only the latter that provides memcpy (which otherwise throws ‘undefined’ errors).

**Comment by aferrero2707** [comment]
I've just pushed the proposed fix to the stable branch.

Thanks!

**Comment by Joermungand** [comment]
Great! Updated in AUR. Thanks!

**Comment by aferrero2707** [comment]
Very good! Closing the issue then...
